### ISSUE TITLE
Build error when defining BL_BUILD_NO_FIXED_PIPE

### ISSUE THREAD

**Issue by LuizZak** [blend2d/blend2d#10]
The following line causes a build error due to an undefined member `DST_PTR` when instantiating the template over `BLFixedPipe_Composite_PRGB32_Src_Solid`:

https://github.com/blend2d/blend2d/blob/2c58df4dc688c12722a91266d82a1b4bb47bde19/src/blend2d/fixedpipe/blfixedpiperuntime.cpp#L43

I'm assuming this was supposed to read `DST_BPP`, like above?

Caught this while messing around with the source code.

**Comment by kobalicek** [comment]
Thank you, good catch!

**Comment by kobalicek** [comment]
Closing, this should be ok now
