### ISSUE TITLE
Apple M1 SoC (ARM) support?

### ISSUE THREAD

**Issue by Ptomaine** [blend2d/blend2d#102]
Hello Petr/Fabian,

Do you have any plans on supporting ARM instruction set in the near future? Specifically, Apple M1 SoC?
As far as I remember, you've already had the ARM code in asmjit, but removed it for some reasons.

Thank,
Arlen.

**Comment by kobalicek** [comment]
Yes it's planned. There was never a working ARM support in asmjit in the past, that's why it was removed. However, now there is `aarch64` branch that brings almost complete support. I'm currently working on asmjit part to make AArch64 architecture first class.

**Comment by Ptomaine** [comment]
Thanks! :)
