### ISSUE TITLE
Text stroke causes a dead loop

### ISSUE THREAD

**Issue by firefishu** [blend2d/blend2d#103]
A dead loop occurs when using this font to stroke the text “设”
[Alibaba-PuHuiTi-Bold.otf.zip](https://github.com/blend2d/blend2d/files/6014072/Alibaba-PuHuiTi-Bold.otf.zip)

**Comment by kobalicek** [comment]
I will check this out soon, thanks for the report.

**Comment by kobalicek** [comment]
Let me know wheter https://github.com/blend2d/blend2d/commit/3f62030c27a1c006ac5bfa547f9d955674b98062 fixes the issue.

**Comment by firefishu** [comment]
> Let me know wheter [3f62030](https://github.com/blend2d/blend2d/commit/3f62030c27a1c006ac5bfa547f9d955674b98062) fixes the issue.

Yes, it worked
