### ISSUE TITLE
Matrix transformations on a path object don't mark it as BL_PATH_FLAG_DIRTY

### ISSUE THREAD

**Issue by Ptomaine** [blend2d/blend2d#104]
After applying transformations on a path (like path.translate(...)), it doesn't set the path flag as BL_PATH_FLAG_DIRTY. This results in the wrong getBoundingBox values since the path info updater returns the old path info on path bounds. As a mitigation, the flags value can be set to BL_PATH_FLAG_DIRTY manually.

Could you please fix the issue?

**Comment by kobalicek** [comment]
Thanks, I have just verified it and it's a bug.

**Comment by Ptomaine** [comment]
Thanks for fixing it :)
