### ISSUE TITLE
Gradient and pattern fills do not work when BLEND2D_NO_JIT is enabled

### ISSUE THREAD

**Issue by electroduck** [blend2d/blend2d#106]
Please let me know if this issue has already been reported, it seems pretty serious so I'm surprised that I haven't seen anything about it.

Expected behavior: Enabling BLEND2D_NO_JIT at build time will result in all fills being performed normally, but at a lower speed.

![expected](https://user-images.githubusercontent.com/1700762/112380939-3ca7f780-8ca7-11eb-83a8-84747ffad503.png)

Actual behavior: If BLEND2D_NO_JIT is enabled at build time, attempting to perform gradient or pattern fills will instead result in solid fills of apparently random colors. In this example, the panel that is supposed to be filled with a stretched rubber duck (a pattern fill) is instead filled with red color, while the button that is supposed to be filled with a linear gradient is instead filled with blue color.

![actual](https://user-images.githubusercontent.com/1700762/112380990-4af61380-8ca7-11eb-8cae-198f4e443710.png)

How to test: When configuring Blend2D, add -DBLEND2D_NO_JIT=1 to the CMake command line. Then, compile and run any program that performs gradient or pattern fills. Observe the results of the fills.

I have found that this problem occurs on 32-bit Windows, 64-bit Windows, and WebAssembly. I do not know if it occurs on other platforms, but my guess is that it not OS-related. It makes Blend2D not an option in any situation where ASMJIT does not work, i.e. any architecture other than 32-bit or 64-bit x86.

**Comment by kobalicek** [comment]
This feature is experimental and not fully finished.

It was added to test Blend2D on ARM. However, not all composition modes and fetchers are implemented without JIT.

**Comment by kobalicek** [comment]
This is something that should work on the current master, can you verify?
