### ISSUE TITLE
Feature Request: Loading SVG files

### ISSUE THREAD

**Issue by AndrewAPrice** [blend2d/blend2d#107]

**Comment by kobalicek** [comment]
I don't think that this has a chance to be part of Blend2D. The goal is to make library usable as an SVG renderer backend, but not to be the SVG renderer itself. To render SVG you need XML, CSS, etc...

**Comment by kobalicek** [comment]
Closing, as SVG may be provided by additional library - it should not be a part of Blend2D.

Thanks for the idea, I will consider creating a small SVG engine myself when I get a little bit more time.
