### ISSUE TITLE
Version is not being updated

### ISSUE THREAD

**Issue by Oldes** [blend2d/blend2d#110]
Although Blend2D is officially [bata 16](https://blend2d.com/download.html), the internal [BL_VERSION is still just 0.0.1](https://github.com/blend2d/blend2d/blob/41e4f9f440ed2cef9f3d19699a14e9e7b11144e4/src/blend2d/api.h#L241).

**Comment by kobalicek** [comment]
True, next beta release will have this fixed

**Comment by kobalicek** [comment]
It should be updated by now - closed by https://github.com/blend2d/blend2d/commit/be3c0583427f706b97b9c3fdbd8e637c36bee6d7
