### ISSUE TITLE
Pattern fill: output pixels have alpha 254 where it should be 255 (fully opaque)

### ISSUE THREAD

**Issue by fjpietr** [blend2d/blend2d#112]
Wrong behaviour from the attached snippet. Filling an opaque shape with an opaque pattern should result in pixels with alpha == 255 except at AA borders, but both the snippet in the fiddler and my app gives 254 instead.

[pattern fill alpha bug.txt](https://github.com/blend2d/blend2d/files/6748809/pattern.fill.alpha.bug.txt)

**Comment by fjpietr** [comment]
More test: regular unstretched blits are ok, blits with scaling fail with alpha == 254.

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/blend2d/blend2d/commit/223a77896aa312f2f7e8f8061e9c95959fbe2969
