### ISSUE TITLE
Closing path twice causes it to draw nothing

### ISSUE THREAD

**Issue by LostVector** [blend2d/blend2d#115]
Should closing a path twice cause it to behave as if it is empty?

Example would be:

> BLPath path;
> path.moveTo(26, 31);
> path.cubicTo(642, 132, 587, -136, 25, 464);
> path.close()
> path.close()

Drawing this path with a context acts like a no-op.

For context, I'm trying out blend2d as a cross platform replacement for another drawing engine and this behavior is breaking some tests since our other drawing API doesn't have the same issue.  Is there a reason for the behavior or perhaps a way to work around it?

**Comment by yzrmn** [comment]
Looks like fills are rendered, but strokes are not: https://fiddle.blend2d.com/

```
BLImage render(const BLContextCreateInfo& cci) {
  BLImage img(512, 512, BL_FORMAT_PRGB32);
  BLContext ctx(img, cci);
  ctx.clearAll();

  BLPath path;
  path.moveTo(26, 31);
  path.cubicTo(642, 132, 587, -136, 25, 464);
  path.close();
  path.close();

  ctx.setFillRule(BL_FILL_RULE_EVEN_ODD);
  ctx.setFillStyle(BLRgba32(0xFFFFFFFF));
  ctx.fillPath(path);

  ctx.setStrokeStyle(BLRgba32(0xFFFF8000));
  ctx.setStrokeWidth(3);
  ctx.strokePath(path);

  return img;
}
```

**Comment by kobalicek** [comment]
Yeah the geometry is refused, because stroker expects `moveTo`, and not `close`. This can be fixed, but on the other hand the path is wrong and the question is how much wrong should various geometry processors process.

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/blend2d/blend2d/commit/831483b1f2576376fe1dfd08a1dd7cb06982a894
