### ISSUE TITLE
`strokePath` crashed in a corner case.

### ISSUE THREAD

**Issue by ZhouYuChen** [blend2d/blend2d#118]
`BLContext::strokePath` crashes in a random generated path. But if the path was rotated or perturbated a bit, the program works fine.

```cpp
#include <blend2d.h>

int main() {
  BLImage img(640, 640, BL_FORMAT_A8);
  BLContext ctx(img);
  BLPath path;
  path.moveTo(BLPoint(337.46392822265625, 17.5000762939453125));
  // it will be ok to change 0.0016326904296875 to 0.1 or a random number.
  path.lineTo(BLPoint(337.216827392578125, 0.0016326904296875)); 
  path.lineTo(BLPoint(337.51043701171875, -19.34902191162109375));
  ctx.strokePath(path);
}
```

It will crash with a `Segmentation fault` if it was compiled with blend2d in release mode.

If it was compiled with blend2d in debug mode, an assertion error reported:
```
[Blend2D] ASSERTION FAILURE: 'uint32_t(_ey0) >= _bandOffset' at '.../raster/analyticrasterizer_p.h' [line 483]
```

**Comment by x10000year** [comment]
@kobalicek  Can it be fixed? Thanks

**Comment by kobalicek** [comment]
Yeah I will debug this, sorry guys I let you waiting.

**Comment by kobalicek** [comment]
I have found an issue - I will see whether it makes sense to hotfix this now or whether it will be part of next beta release, which is coming soon.

**Comment by x10000year** [comment]
btw, can you provide drawPoints() functionality, just like what skia provides.
