### ISSUE TITLE
Is it feasible to build GUI framework out of blend2d

### ISSUE THREAD

**Issue by mickeymgk** [blend2d/blend2d#119]
Is it possible to render the BLImage output of this library directly to opengl backend? The same approach is used in nanovg to render ui components. I know this might be out of context of this library but just wanted to get thoughts on it

**Comment by kobalicek** [comment]
I you mean rending directly to an opengl texture in GPU RAM via opengl commands then no - Blend2D doesn't support this.

You can render to a buffer and upload the data into a texture, that's possible, but the rendering is software accelerated and requires a buffer accessible to CPU to render into it.

**Comment by mickeymgk** [comment]
Thanks closing this as it answered my question.
