### ISSUE TITLE
realtime rendering?

### ISSUE THREAD

**Issue by doongjohn** [blend2d/blend2d#131]
can blend2d be used as a realtime rendering library? if so, is there any examples?

**Comment by kobalicek** [comment]
Yes, why not? There is bunch of qt demos that are "real time" I think :)

Depends on the complexity of what you render of course, but in general vector arg, maps, UIs, etc... can all be rendered real time.

**Comment by Daandelange** [comment]
The [ofxBlend2D](https://github.com/Daandelange/ofxBlend2D/) wrapper is realtime (game-engine-like) and can render quite a lot of calls at 60 FPS.
As my project was using an insanely amount of 2d vector bezier points (±183k), I made an asynchronous rendering function for editing and previewing "real-time", with a render process to export the final animation.
Here's a performance comparison demo : [GPU rendering vs Blend2D rendering](https://www.youtube.com/watch?v=bCTa-FaU3ds).
