### ISSUE TITLE
blGradientGetExtendMode missing const

### ISSUE THREAD

**Issue by JouriM66** [blend2d/blend2d#132]
blGradientGetExtendMode must be:

```
BL_API BLExtendMode BL_CDECL blGradientGetExtendMode(const BLGradientCore* self) BL_NOEXCEPT_C BL_PURE;
```

but "const" is missing.

**Comment by kobalicek** [comment]
Thanks, this will be fixed

**Comment by kobalicek** [comment]
Should be collaterally fixed by https://github.com/blend2d/blend2d/commit/63db360c7eb2c1c3ca9cd92a867dbb23dc95ca7d
