### ISSUE TITLE
Filling with pattern traps on some conditions.

### ISSUE THREAD

**Issue by JouriM66** [blend2d/blend2d#133]
Cant reproduce it on Fiddie.  It works where.
Code:
```
BLImage render( const BLContextCreateInfo& cci )
{ BLImage pimg( 7, 7, BL_FORMAT_PRGB32 );
  BLContext pctx( pimg, NULL );

  //Make cross lines
  pctx.setCompOp( BL_COMP_OP_SRC_COPY );
  pctx.setFillStyle( BLRgba( 1, 1, 1, 0 ) );
  pctx.fillRect( BLRect( 0, 0, 7, 7 ) );
  pctx.setCompOp( BL_COMP_OP_SRC_OVER );
  pctx.setStrokeStyle( BLRgba( 1, 0, 0 ) );
  pctx.strokeLine( 7, 0, 0, 7 );
  pctx.setStrokeStyle( BLRgba( 0, 0, 1 ) );
  pctx.strokeLine( 0, 0, 7, 7 );
  pctx.flush( BL_CONTEXT_FLUSH_SYNC );

  //patetrn
  BLPattern patt( pimg );

  // Create a destination image and rendering context.
  BLImage img( 200, 200, BL_FORMAT_PRGB32 );
  BLContext ctx( img, NULL );

  ctx.setFillStyle( BLRgba( 1, 1, 1 ) );
  ctx.fillRect( BLRect( 0, 0, 500, 500 ) );

  ctx.translate( 100, 100 );
  ctx.rotate( 3.14159265358979323846 / 180 * 360 );

  //if is set to pattern fill it traps with 360 degree rotation
  ctx.setFillStyle( patt );
  //ctx.setFillStyle( BLRgba(0,0,1) );

  ctx.fillRect( BLRect( 0, 0, 100, 100 ) );

  return img;
}
```

Conditions to trap:
1. pattern fill used
2. set non-zero translation (any nonzero works) 
3. set rotation angle to 360 degrees (any other angles in 0..359 works fine)

It works on Fiddie, but if I insert it into any Blend2D executables (I just add it to bl_test_fuzzer.cpp, since Blend have no any other configured exapmples, and call it from main), it traps with:
```
Exception thrown at 0x00B40C26 in bl_test_fuzzer.exe: 0xC000001D: Illegal Instruction.
Unhandled exception at 0x00B40C26 in bl_test_fuzzer.exe: 0xC000001D: Illegal Instruction.
```

the code where is (invalid code is line with vpsrad):

```
00B40C21 C5 F9 70 FF 50       vpshufd     xmm7,xmm7,50h  
00B40C26 62 F1 7D 08 72 64 24 09 1F vpsrad      xmm0,xmmword ptr [esp+90h],1Fh  
00B40C2F C5 F9 EF 84 24 90 00 00 00 vpxor       xmm0,xmm0,xmmword ptr [esp+90h]  
```

I have no idea what does this code do and how it works so I cant dig deeper.

To test it I done next steps:
1. Download fresh clone from github
2. Run tools\configure-vs2019-x86.bat
3. Open build_vs2019_x86\blend2d.sln in Visual Studio 2019
4. Add code above to bl_test_fuzzer.cpp
5. Press build

After all was successfully build I run bl_test_fuzzer.exe and see this exception in Visual Studio.

In case its some sort of precessor specific here is my data gathered by latest CPUz:
[TANK.txt](https://github.com/blend2d/blend2d/files/8102578/TANK.txt)

**Comment by kobalicek** [comment]
Thanks, this seems like a bug in asmjit - it generates an AVX-512 instruction, but it shouldn't.

**Comment by kobalicek** [comment]
Would you be able to test this with asmjit's [ra_mem_usage](https://github.com/asmjit/asmjit/tree/ra_mem_usage) branch?

**Comment by JouriM66** [comment]
No, im not able.
Have no such branch in asmjit repo.

**Comment by kobalicek** [comment]
Ok thanks! I'm closing this issue as I think it has been fixed by that asmjit change - if you face the problem again please reopen or create another issue.
