### ISSUE TITLE
website is down ? :/

### ISSUE THREAD

**Issue by LifeIsStrange** [blend2d/blend2d#136]

**Comment by kobalicek** [comment]
The server looks healthy, can you describe any problem with the website?

**Comment by andrewwa0** [comment]
Looks good on my end in AU
  
  
  
  
  
  
  

  
  
>

**Comment by LifeIsStrange** [comment]
https://blend2d.com says "Hmmm… can't reach this page" 
"The connection was reset."
except my connection was not reset and is perfectly fine. It might be that this website would be blocked over a firewall? Weird this never happen to me and I was able to access it, at least a year ago (France, 4G network)

**Comment by kobalicek** [comment]
To be honest I have no idea what that error means :( The machine is hosted by Hetzner, I haven't changed any firewall settings or anything. Please inform me if the problem persists, maybe it's some issue that is unrelated and happens on the way.

**Comment by LifeIsStrange** [comment]
maybe the server require HSTS?
spoiler I'm pretty sure the website will work on my WIFI vs 4G, I'll tell update u tomorrow

**Comment by kobalicek** [comment]
So, is it still down or it's ok now?

**Comment by kobalicek** [comment]
Closing, please reopen if you have any problems with the website. It should work, I'm not aware of any blocking or traffic filtering.

**Comment by LifeIsStrange** [comment]
Yes it's still blocked on my French 4G network however it works on WIFI
