### ISSUE TITLE
Possible bug with BLContext::setCompOp()

### ISSUE THREAD

**Issue by ReneMuala** [blend2d/blend2d#137]
In this demo, the objective is to use the composition operator BL_COMP_OP_DST_IN to _mask_ the first rectangle using the second rectangle.
```
int main(int argc, const char * argv[]) {
    BLImage img = BLImage(500,500,BL_FORMAT_PRGB32);
    
    BLContext ctx = BLContext(img);
    
    ctx.setCompOp(BL_COMP_OP_SRC_OVER);
    ctx.setFillStyle(BLRgba32(0xFFFF00FF));
    ctx.fillRect(100, 100, 250, 250);
    
    ctx.setCompOp(BL_COMP_OP_DST_IN);
    ctx.setFillStyle(BLRgba32(0xFFFFFF00));
    ctx.fillRect(150, 150, 250, 250);
    ctx.end();
    
    img.writeToFile("output.png");
    return 0;
}
```
However, after the process, the second rectangle just disappears, without any change in the first.

###### _As expected..._

![output](https://user-images.githubusercontent.com/64354602/157556993-67c6d7c2-b2cf-4fb8-b9aa-701b9b6725ec.png)

###### _The problem..._

![output](https://user-images.githubusercontent.com/64354602/157556438-e0d42a77-cadf-40fd-89ad-3858f0d6ef67.png)

###### _Using libcairo..._

![expected-output](https://user-images.githubusercontent.com/64354602/157556655-9d78d325-002a-46e3-9619-61194beaf27f.png)

Tested on macOS 11.2.3.

###### (Translated by google)

**Comment by kobalicek** [comment]
This is actually not a bug. When you draw with Blend2D, only the area defined by a path, rectangle, or image is composited. However, Cairo composites the whole non-clipped area. I personally consider behavior of Blend2D better.

Changing the second operator to `BL_COMP_OP_SRC_COPY` (and Cairo equivalent in your Cairo sample) should make it clear what is happening in both Blend2D and Cairo.

**Comment by ReneMuala** [comment]
Thanks for the explanation, the purpose of the test was to use a path to cut the image in the current context. Apparently this is not possible using operators, I guess.

is there another way to do this in blend2d?

###### (Translated by google)

**Comment by ReneMuala** [comment]
After a few tries I came to this slow solution:

```
int main(int argc, const char * argv[]) {
    BLImage img = BLImage(500,500,BL_FORMAT_PRGB32);
    BLImage img2 = BLImage(500,500,BL_FORMAT_PRGB32);
    
    BLPattern pattern;
    
    BLContext ctx = BLContext(img);
    
    ctx.setCompOp(BL_COMP_OP_SRC_OVER);
    ctx.setFillStyle(BLRgba32(0xFFFF00FF));
    ctx.fillRect(100, 100, 250, 250);
    
    ctx.end();
    
    pattern.create(img);
    
    ctx = BLContext(img2);
    
    ctx.setFillStyle(pattern);
    ctx.fillRect(150, 150, 250, 250);
    
    ctx.end();
    
    img = img2;
    
    img.writeToFile("output.png");
    return 0;
}
```

If there is a faster way to do this, please let me know.

**Comment by kobalicek** [comment]
I think there is no way at the moment to do exactly this operation as a single operation. I think that it would be interesting to have NON_ZERO_REVERSE and EVEN_ODD_REVERSE fill rules - with these the composition like this would be possible.
