### ISSUE TITLE
Create a blank image and fill it with fonts

### ISSUE THREAD

**Issue by HowToExpect** [blend2d/blend2d#139]
`int main()
{
    string strText = "ABCDEEG";
    int w = 200;
    int h = 50;
    int fontSize = 24;

    BLFontFace face;
    face.createFromFile("SourceHanSansSC-Regular.otf");

    BLFont font;
    font.createFromFace(face, fontSize);

    BLFontMetrics fm = font.metrics();

    IplImage *img = cvCreateImage(cvSize(w, h), 8, 4);

    cvSetZero(img);
    BLImage bl;
    bl.createFromData(w, h, BL_FORMAT_PRGB32, img->imageData, img->widthStep);

    BLContext ctx(bl);
    ctx.setFillStyle(BLRgba32(0xFFFFFFFF));

    int y = (h - fontSize) / 2 + fm.ascent - fm.descent;
    ctx.fillUtf8Text(BLPoint(10, y), font, strText.c_str());

    ctx.end();

    cv::Mat mat;
    mat = cv::cvarrToMat(img);

    cv::imwrite("2.png", mat);
    bl.writeToFile("3.png");

    return 0;
}`

**Comment by HowToExpect** [comment]
![2](https://user-images.githubusercontent.com/101079181/159234352-f43ec958-9710-42a7-b770-03cf01c320dd.png)
![3](https://user-images.githubusercontent.com/101079181/159234355-ecb42bb6-bbb6-4f12-a713-a6655933f940.png)

**Comment by HowToExpect** [comment]
![3](https://user-images.githubusercontent.com/101079181/159234924-47b1374b-a7c1-4aa6-8d62-6d01eb312d2b.png)
![2](https://user-images.githubusercontent.com/101079181/159234930-b0aef3ff-7a35-4e8f-a3e7-9ef39922d257.png)

**Comment by kobalicek** [comment]
Blend2D is using premultiplied 32-bit ARGB pixel format - in little endian it's BGRA in memory - I think your cv::imwrite() uses a different format.

**Comment by kobalicek** [comment]
I'm closing this issue as I don't think there is an issue in Blend2D, rather interfacing with opencv in this case. `BLPixelConverter` can be used to perform pixel conversion to foreign formats.
