### ISSUE TITLE
BLContext::fillAll different bahavior with cairo_paint

### ISSUE THREAD

**Issue by randomguy76845** [blend2d/blend2d#14]
Is fillAll supposed to be equivalent with cairo_paint?
If yes, then Blend2D doesn't respect any transformation like this [cairo sample](https://www.cairographics.org/samples/image/).

**Comment by kobalicek** [comment]
fillAll is supposed to fill everything with the current fill style, transformations have no effect here.

**Comment by randomguy76845** [comment]
Thanks
