### ISSUE TITLE
ios appstore - options not allowed to be embedded in bitcode are detected in the submission.

### ISSUE THREAD

**Issue by kikaxa** [blend2d/blend2d#143]
After updating, we got a reject
`ITMS-90562: Invalid Bundle - The app cannot be processed because options not allowed to be embedded in bitcode are detected in the submission. It is likely that you are not building the app with the toolchain provided in Xcode. Rebuild your entire app with the latest GM Xcode and submit the app again.` 
relating to some compilation flags.

blanket-removing/reverting the options
`-fno-trapping-math -fno-finite-math-only -fno-enforce-eh-specs`
fixes the submission again for us

related line/clause in cmake(AppleClang):
`elseif ("${CMAKE_CXX_COMPILER_ID}" MATCHES "^(GNU|Clang|AppleClang)$")`

**Comment by kobalicek** [comment]
Interesting, thanks!

BTW I would like to keep these flags, but I can add a cmake option to not add these, would that be okay?

**Comment by kikaxa** [comment]
I suggest enabling this option by making the default a `IOS` value

**Comment by kobalicek** [comment]
BTW I don't have any experience targeting iOS with CMake, is `CMAKE_SYSTEM_NAME` the option I would use for this?

**Comment by kikaxa** [comment]
It is literally using `IOS` var 😀 e.g.
set(GENERATE_SHADERS (IOS) CACHE BOOL "...")
