### ISSUE TITLE
kCFFValueStackSizeV1 is small

### ISSUE THREAD

**Issue by miaotianlei** [blend2d/blend2d#145]
Today I use blend2d to draw text, but some chars didn't drawed, blend2d return BL_ERROR_FONT_CFF_INVALID_DATA error. I debug it, I find the error occur on "if (BL_UNLIKELY(++vIdx >= kCFFValueStackSizeV1)) goto InvalidData;", it has beyond max value when get operation code. But it only use some bytes, Others are invalid. The buffer was filled some invalid data, but it no store space when get valid value. I increase buffer space to 128. Am I right? If modify verctor type, it can push more data. Please sure my changes. Thank you!

**Comment by kobalicek** [comment]
I'm not sure where is the problem at the moment. CFF has a specification here:

https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf

And the arguments stack is limited to 48 values. So instead of increasing the limit above the specification I would like to make sure that there is not some other issue (for example, maybe every subroutine has such a limit, but I have no idea atm).

**Comment by miaotianlei** [comment]
Argument stack is 48 in document. I don't sure if it include operation code. 
https://aicplatform.blob.core.chinacloudapi.cn/mediadata/av_server/data/others/SourceHanSansCN-Bold.otf
The link is my font file. Help me to verify it. The opertation code is on 49 position.
The font file is chinese. You can try "猫","猪”, they will throw error. Thank you.

**Comment by miaotianlei** [comment]
> I'm not sure where is the problem at the moment. CFF has a specification here:
> 
> https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf
> 
> And the arguments stack is limited to 48 values. So instead of increasing the limit above the specification I would like to make sure that there is not some other issue (for example, maybe every subroutine has such a limit, but I have no idea atm).

Can you help me to check this problem? The link is font file.
https://aicplatform.blob.core.chinacloudapi.cn/mediadata/av_server/data/others/SourceHanSansCN-Bold.otf

**Comment by kobalicek** [comment]
I checked it out and I think I have fixed this issue by https://github.com/blend2d/blend2d/commit/239a4ba34b108f170516b59ead9417bae60b7f74

Can you verify?

**Comment by miaotianlei** [comment]
> I checked it out and I think I have fixed this issue by [239a4ba](https://github.com/blend2d/blend2d/commit/239a4ba34b108f170516b59ead9417bae60b7f74)
> 
> Can you verify?

I updated your codes. Them ware well. Thank you!
