### ISSUE TITLE
underlinePosition and strikethroughPosition

### ISSUE THREAD

**Issue by miaotianlei** [blend2d/blend2d#146]
Today I draw under line on text. I use this value, it can't draw the under of text. I try check codes,  "int underlinePosition = -(post->underlinePosition() + underlineThickness);", I don't understand why add underlineThickness and reverse value. I check document underline is base on baseline. I feel underline should be negative. The strikethroughPosition is same problem with it .

Please help me . Thank you.

**Comment by kobalicek** [comment]
The information presented by Blend2D is converted to Blend2D coordinate system - if it used a TTF/OTF coordinate system it would be reversed in Y direction.

I'm not sure I follow the question, do you have an image showing what is wrong in the calculations? The values come from a font file

**Comment by miaotianlei** [comment]
> The information presented by Blend2D is converted to Blend2D coordinate system - if it used a TTF/OTF coordinate system it would be reversed in Y direction.
> 
> I'm not sure I follow the question, do you have an image showing what is wrong in the calculations? The values come from a font file

Thank you. I follow your mean to check codes. I had understand your mean. But I still don't understand underline position, need to add half of underline thickness or subtract it?  "This is the suggested distance of the top of the underline from the baseline" , How to understand the top of underline?

**Comment by kobalicek** [comment]
I understand underline position, and overline position, as a coordinate you add to the baseline.

I would check out the documentation here:

  - https://docs.microsoft.com/en-us/typography/opentype/spec/post#header
  - https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ystrikeoutsize

As those are specifying the behavior of these properties - Blend2D just presents these to the users.

**Comment by miaotianlei** [comment]
I think I has understand through codes and your comment. Thank you.
