### ISSUE TITLE
draw issue

### ISSUE THREAD

**Issue by miaotianlei** [blend2d/blend2d#147]
I find one problem. Firstly, I use red color to draw a rect, the color's alpha is 255, then I draw image, the image has zeor alpha, but rgb has value in same pixel, the draw result is the region of source image is transparent, I hope it display background image. I want to why?

**Comment by miaotianlei** [comment]
auto img_data = image->imageData();
        for (int row = 0; row < img_data->height(); row++) {
            for (int col = 0; col < img_data->width(); col++) {
                char* a = (char*)img_data->data() + (row * img_data->width() + col) * 4 + 3;
                *a = 0;
            }
        }
These are test codes. Set image alpha channel to zero. Draw this image on canvas, it will set image region to transparent. The canvas is red background.

**Comment by miaotianlei** [comment]
I disable jit, I see these codes
// Dca' = Sca + Dca.(1 - Sa)
  // Da'  = Sa  + Da .(1 - Sa)
  static BL_INLINE PixelType op_prgb32_prgb32(PixelType d, PixelType s) noexcept {
    return s + (d.unpack() * Repeat{BLPixelOps::Scalar::neg255(s.a())}).div255().pack();
  }

Do the operator has problem? The follow code is from other, it also is mix pixel.
mix_a = dst_a + src_a - dst_a * src_a;
dst_rgb = (dst_rgb * dst_a * (1 - src_a) + src_rgb * src_a) / mix_a

**Comment by miaotianlei** [comment]
I use BL_CONTEXT_CREATE_FLAG_DISABLE_JIT flag, it will only display color, can't display image.

**Comment by miaotianlei** [comment]
auto s_a = (float)s.a() / 255.0, d_a = (float)d.a() / 255.0;
    auto mix_a = s_a + d_a - s_a * d_a;
    auto mix_r = (uint32_t)((s.r() * s_a + d.r() * d_a * (1.0 - s_a)) / (mix_a == 0 ? 1.0 : mix_a));
    auto mix_g = (uint32_t)((s.g() * s_a + d.g() * d_a * (1.0 - s_a)) / (mix_a == 0 ? 1.0 : mix_a));
    auto mix_b = (uint32_t)((s.b() * s_a + d.b() * d_a * (1.0 - s_a)) / (mix_a == 0 ? 1.0 : mix_a));
    auto mix_aa = (uint32_t)(mix_a * 255);
    return PixelType{mix_aa << 24 | mix_r << 16 | mix_g << 8 | mix_b};


 I modify codes in CompOp_SrcOver_Op's op_prgb32_prgb32 function. But I won't display image when disable jit

**Comment by miaotianlei** [comment]
https://fiddle.blend2d.com/
BLImage render(const BLContextCreateInfo& cci) {
  BLImage img(256, 256, BL_FORMAT_PRGB32);
  BLContextCreateInfo ci;
    ci.flags = BL_CONTEXT_CREATE_FLAG_DISABLE_JIT ;
  BLContext ctx(img, ci);

  ctx.clearAll();

  BLImage tex[2];
  tex[0].readFromFile("textures/tex16.jpg");
  tex[1].readFromFile("textures/tex24.jpg");

  //ctx.setCompOp(BL_COMP_OP_SRC_COPY);
  ctx.blitImage(BLPointI(0, 0), tex[0], BLRectI(0, 0, 160, 160));
  //ctx.setCompOp(BL_COMP_OP_MULTIPLY);
  ctx.blitImage(BLPointI(96, 96), tex[1], BLRectI(0, 0, 160, 160));

  return img;
}

Demon also can't display image

**Comment by kobalicek** [comment]
Disabling JIT is experimental, it would not work for most cases, you should test with JIT on x86/amd64 ISAs

**Comment by miaotianlei** [comment]
> Disabling JIT is experimental, it would not work for most cases, you should test with JIT on x86/amd64 ISAs

I only disable jit to look if the problem exists. My problem occurs while open jit feature. For example, one pixel, it's alpha is 0, the value of rgb greater than 0, Mix result is transparent on BL_COMP_OP_SRC_COPY mode. I feel it use source image's alpha  value. 

Please help me check it, I don't understand jit librabry, I don't know how to modify it or my method is wrong. 

Thank you.

**Comment by kobalicek** [comment]
I'm not sure I understand the problem though.

Blend2D uses premultiplied pixels - this means that each component is multiplied with alpha. If alpha is zero, all components are zero - a fully transparent pixel has no color information in images, it's lost simply by multiplying it by zero alpha.

Changing alpha in images like this is wrong - to change the alpha, you have to first unpremultiply the pixel, change the value, and premultiply it, so it becomes:

```
uint32_t a;
uint32_t r ;
uint32_t g;
uint32_t b;

// Unpremultiply (roughly)
r = (r * 255) / a;
g = (g * 255) / a;
b = (b * 255) / a;

// manipulate components
a = 0;

// premultiply
r = (r * a) / 255;
g = (g * a) / 255;
b = (b * a) / 255;
```

If you set a to zero, RGB becomes zero as well.

**Comment by miaotianlei** [comment]
I'm sorry. I write an error, I use BL_COMP_OP_SRC_OVER mode.  I do following steps:
1. I create canvas with transparent image.For example 1920 * 1080 image, all pixels value are zero. 
2. I draw red background on canvas. 
3. I modify alpha of image to zero, but it's rgb is not zero. For example: r = 128, g = 234, b = 15, a = 0.
4. I choose BL_COMP_OP_SRC_OVER mode(default mode).
5. I draw the modified image on canvas.
 
I complete these operators, I find the override region is empty(transparent). 
I think can't clean up the background, beacause the alpha  of background is 255. 
BL_COMP_OP_SRC_OVER mode only draw image on canvas, It need to mix together between source image pixel value and canvas pixel value.

**Comment by miaotianlei** [comment]
I feel I had know reason.  I use createFromData function to create image data. The input data need to be converted premultiplied. 
Please help sure how fill image info on little-endian and big-endian. The image is png format.

big endian: r << 24, g << 16，b << 8, a << 0
little endian: r << 0, g << 8， b << 16, a << 24

Is this right? thank you.


const BLFormatInfo blFormatInfo[BL_FORMAT_RESERVED_COUNT] = {
  #define U 0 // Used only to distinguish between zero and unused.
  { 0 , blFormatFlagsStatic(0 ), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Public:NONE>
  { 32, blFormatFlagsStatic(1 ), {{ { 8, 8, 8, 8 }, { 16, 8 , 0 , 24 } }} }, // <Public:PRGB32>
  { 32, blFormatFlagsStatic(2 ), {{ { 8, 8, 8, U }, { 16, 8 , 0 , U  } }} }, // <Public:XRGB32>
  { 8 , blFormatFlagsStatic(3 ), {{ { U, U, U, 8 }, { U , U , U , 0  } }} }, // <Public:A8>
  { 32, blFormatFlagsStatic(4 ), {{ { 8, 8, 8, U }, { 16, 8 , 0 , U  } }} }, // <Internal:FRGB32>
  { 32, blFormatFlagsStatic(5 ), {{ { 8, 8, 8, 8 }, { 16, 8 , 0 , 24 } }} }, // <Internal:ZERO32>
  { 0 , blFormatFlagsStatic(6 ), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(7 ), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(8 ), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(9 ), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(10), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(11), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(12), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(13), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(14), {{ { U, U, U, U }, { U , U , U , U  } }} }, // <Reserved>
  { 0 , blFormatFlagsStatic(15), {{ { U, U, U, U }, { U , U , U , U  } }} }  // <Reserved>
  #undef U
};

why fix these values? Don't you need to judge big or little?

**Comment by kobalicek** [comment]
Blend2D is endian dependent - 32-bit RGBA format is `[R<<16, G<<8, B<<0, A<<24]` - which has a different layout in memory on little vs big endian platforms

**Comment by miaotianlei** [comment]
> Blend2D is endian dependent - 32-bit RGBA format is `[R<<16, G<<8, B<<0, A<<24]` - which has a different layout in memory on little vs big endian platforms.
> 
> BTW I still don't understand the problem, maybe you can share a fiddle that demonstrates the issue or write a code that uses a different library that does what you intend - that would make it easier to help from my side.

"else if (colorType == BL_PNG_COLOR_TYPE6_RGBA) {
      pngFmt.flags |= BL_FORMAT_FLAG_RGBA;
      pngFmt.rSize = 8; pngFmt.rShift = 24;
      pngFmt.gSize = 8; pngFmt.gShift = 16;
      pngFmt.bSize = 8; pngFmt.bShift = 8;
      pngFmt.aSize = 8; pngFmt.aShift = 0;
    }"
These codes are from pngcodec.cpp in blend2d. I think it is default little endian. No codes judge if big endian or little endian.

The pixel's color value position is |A|B|G|R| from low address to hight address in memory on little endian according to codes. 
if I use big big endian, is the positon right?

**Comment by kobalicek** [comment]
You have missed a very important line:

```c++
  if (BL_BYTE_ORDER_NATIVE == BL_BYTE_ORDER_LE)
    pngFmt.flags |= BL_FORMAT_FLAG_BYTE_SWAP;
```

This ensures that the components are properly swapped depending on endianness.

**Comment by miaotianlei** [comment]
Oh my god, I missed  a very important line. 

Codes resolve png file to |A|B|G|R| byte order in memory. Do all png parsers have same byte order?

**Comment by miaotianlei** [comment]
Oh my god, I missed a very important line.

PNG file is parsed to  |R|G|B|A| format in memory. 
It will add swap flag if native is little endian. 
Why not to default little endian? We use x86 platform at most of time.

Opencv needs input format that is |B|G|R|A| order in memory.
