### ISSUE TITLE
Compilation error in gcc C++20

### ISSUE THREAD

**Issue by toge** [blend2d/blend2d#149]
I'm using blend2d following environments.
- Fedora Linux 36
- gcc 12.1.1
- blend2d beta18

I get a compile error with C++20 (`g++ -std=c++20`).

```C++
In file included from .../src/blend2d/api-build_p.h:289,
                 from .../src/blend2d/context.cpp:6:
.../src/blend2d/api-internal_p.h:239:15: error: expected unqualified-id before ‘const’
  239 |   __VA_ARGS__(const __VA_ARGS__& other) = delete;                             \
      |               ^~~~~
.../src/blend2d/raster/../support/scopedbuffer_p.h:85:3: note: in expansion of macro ‘BL_NONCOPYABLE’
   85 |   BL_NONCOPYABLE(BLScopedBufferTmp<N>)
      |   ^~~~~~~~~~~~~~
```

With C++17 (`g++ -std=c++17`) the problem does not occur. 
This seems to be a problem when expanding BL_NONCOPYABLE.

Here is sample code.

```C++
#define BL_NONCOPYABLE(...)                                                   \
  __VA_ARGS__(const __VA_ARGS__& other) = delete;                             \
  __VA_ARGS__& operator=(const __VA_ARGS__& other) = delete;

template<int N>
class A {
public:
  BL_NONCOPYABLE(A<N>)

  A() {}

  int a;
};

int main() {
  A<5> a{};

  return 0;
}
```

When it is expanded, I get the following, and an error occurs at the `A<N>(const A<N>& other)` part.

```C++
template<int N>
class A {
public:
  A<N>(const A<N>& other) = delete; A<N>& operator=(const A<N>& other) = delete;

  A() {}

  int a;
};

int main() {
  A<5> a{};

  return 0;
}
```

The following code would eliminate the compile error.
Is it possible to solve it?

```C++
template<int N>
class A {
public:
  A(const A<N>& other) = delete; A<N>& operator=(const A<N>& other) = delete;

  A() {}

  int a;
};

int main() {
  A<5> a{};

  return 0;
}
```

**Comment by kobalicek** [comment]
Let me know whether https://github.com/blend2d/blend2d/commit/2574d90ebc61b5195491cc79bfa6da162084242b fixes the issue.

**Comment by toge** [comment]
Thank you for the quick response!

It is working fine.
There are two places to fix in the other files.
- src/blend2d/support/arenahashmap_p.h.
- src/blend2d/support/scopedbuffer_p.h.

Could you fix these also?

**Comment by kobalicek** [comment]
yeah, should be fixed

**Comment by toge** [comment]
@kobalicek 
Thanks a lot!
