### ISSUE TITLE
Blend2d Cairo

### ISSUE THREAD

**Issue by miaotianlei** [blend2d/blend2d#150]
Cairo without opengl:
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Cairo               | CompOp      | Style         | 8x8   | 16x16 | 32x32 | 64x64 |128x128|256x256|
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|FillRectA           | SrcOver     | Pattern_BI    | 1.2   | 1.3   | 1.8   | 4.5   | 13    | 46    |
|FillRectU           | SrcOver     | Pattern_BI    | 3.2   | 5.8   | 11    | 20    | 59    | 197   |
|FillRectRot         | SrcOver     | Pattern_BI    | 11    | 31    | 72    | 176   | 467   | 1405  |
|FillRoundU          | SrcOver     | Pattern_BI    | 11    | 27    | 54    | 83    | 124   | 262   |
|FillRoundRot        | SrcOver     | Pattern_BI    | 14    | 35    | 76    | 178   | 474   | 1435  |
|FillTriangle        | SrcOver     | Pattern_BI    | 5.2   | 7.6   | 14    | 29    | 68    | 149   |
|FillPolyNZi10       | SrcOver     | Pattern_BI    | 14    | 23    | 43    | 89    | 188   | 410   |
|FillPolyEOi10       | SrcOver     | Pattern_BI    | 14    | 23    | 42    | 89    | 196   | 438   |
|FillPolyNZi20       | SrcOver     | Pattern_BI    | 26    | 44    | 89    | 170   | 348   | 724   |
|FillPolyEOi20       | SrcOver     | Pattern_BI    | 25    | 47    | 84    | 175   | 379   | 848   |
|FillPolyNZi40       | SrcOver     | Pattern_BI    | 44    | 79    | 155   | 323   | 670   | 1362  |
|FillPolyEOi40       | SrcOver     | Pattern_BI    | 42    | 78    | 156   | 335   | 768   | 1676  |
|FillWorld           | SrcOver     | Pattern_BI    | 204   | 274   | 382   | 576   | 973   | 1858  |
|StrokeRectA         | SrcOver     | Pattern_BI    | 5.1   | 5.7   | 6.1   | 8.9   | 15    | 32    |
|StrokeRectU         | SrcOver     | Pattern_BI    | 6.9   | 8.3   | 11    | 14    | 24    | 49    |
|StrokeRectRot       | SrcOver     | Pattern_BI    | 23    | 34    | 56    | 102   | 206   | 453   |
|StrokeRoundU        | SrcOver     | Pattern_BI    | 23    | 37    | 64    | 86    | 100   | 126   |
|StrokeRoundRot      | SrcOver     | Pattern_BI    | 28    | 45    | 81    | 151   | 261   | 513   |
|StrokeTriangle      | SrcOver     | Pattern_BI    | 10    | 13    | 18    | 28    | 47    | 84    |
|StrokePoly10        | SrcOver     | Pattern_BI    | 34    | 51    | 83    | 137   | 233   | 403   |
|StrokePoly20        | SrcOver     | Pattern_BI    | 61    | 91    | 160   | 308   | 585   | 1005  |
|StrokePoly40        | SrcOver     | Pattern_BI    | 120   | 167   | 278   | 556   | 1203  | 2406  |
|StrokeWorld         | SrcOver     | Pattern_BI    | 3871  | 3496  | 3199  | 3059  | 3498  | 4587  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Total               | SrcOver     | Pattern_BI    | 4605  | 4632  | 5145  | 6707  | 10909 | 20480 |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+

+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Cairo               | CompOp      | Style         | 8x8   | 16x16 | 32x32 | 64x64 |128x128|256x256|
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|FillRectA           | SrcCopy     | Pattern_BI    | 0.8   | 0.9   | 1.0   | 1.6   | 3.9   | 19    |
|FillRectU           | SrcCopy     | Pattern_BI    | 4.9   | 7.0   | 10    | 21    | 55    | 174   |
|FillRectRot         | SrcCopy     | Pattern_BI    | 13    | 36    | 82    | 204   | 540   | 1493  |
|FillRoundU          | SrcCopy     | Pattern_BI    | 14    | 36    | 70    | 108   | 151   | 267   |
|FillRoundRot        | SrcCopy     | Pattern_BI    | 15    | 39    | 86    | 199   | 517   | 1493  |
|FillTriangle        | SrcCopy     | Pattern_BI    | 6.8   | 10    | 20    | 45    | 100   | 232   |
|FillPolyNZi10       | SrcCopy     | Pattern_BI    | 17    | 31    | 62    | 134   | 299   | 666   |
|FillPolyEOi10       | SrcCopy     | Pattern_BI    | 17    | 31    | 62    | 139   | 322   | 719   |
|FillPolyNZi20       | SrcCopy     | Pattern_BI    | 29    | 54    | 112   | 245   | 537   | 1150  |
|FillPolyEOi20       | SrcCopy     | Pattern_BI    | 28    | 54    | 117   | 263   | 600   | 1390  |
|FillPolyNZi40       | SrcCopy     | Pattern_BI    | 49    | 89    | 186   | 420   | 939   | 2046  |
|FillPolyEOi40       | SrcCopy     | Pattern_BI    | 48    | 90    | 192   | 452   | 1100  | 2640  |
|FillWorld           | SrcCopy     | Pattern_BI    | 211   | 301   | 427   | 683   | 1255  | 2558  |
|StrokeRectA         | SrcCopy     | Pattern_BI    | 12    | 16    | 33    | 55    | 94    | 182   |
|StrokeRectU         | SrcCopy     | Pattern_BI    | 10    | 13    | 17    | 25    | 42    | 77    |
|StrokeRectRot       | SrcCopy     | Pattern_BI    | 28    | 46    | 81    | 152   | 299   | 556   |
|StrokeRoundU        | SrcCopy     | Pattern_BI    | 31    | 53    | 93    | 133   | 154   | 188   |
|StrokeRoundRot      | SrcCopy     | Pattern_BI    | 33    | 55    | 103   | 191   | 343   | 616   |
|StrokeTriangle      | SrcCopy     | Pattern_BI    | 13    | 17    | 27    | 45    | 84    | 155   |
|StrokePoly10        | SrcCopy     | Pattern_BI    | 39    | 62    | 109   | 203   | 384   | 705   |
|StrokePoly20        | SrcCopy     | Pattern_BI    | 69    | 106   | 203   | 403   | 825   | 1612  |
|StrokePoly40        | SrcCopy     | Pattern_BI    | 133   | 185   | 319   | 687   | 1571  | 3480  |
|StrokeWorld         | SrcCopy     | Pattern_BI    | 3903  | 3516  | 3253  | 3218  | 3740  | 5415  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Total               | SrcCopy     | Pattern_BI    | 4735  | 4860  | 5676  | 8042  | 13965 | 27844 |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+

Cairo with opengl:
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Cairo               | CompOp      | Style         | 8x8   | 16x16 | 32x32 | 64x64 |128x128|256x256|
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|FillRectA           | SrcOver     | Pattern_BI    | 24    | 26    | 44    | 58    | 90    | 419   |
|FillRectU           | SrcOver     | Pattern_BI    | 27    | 28    | 34    | 47    | 105   | 341   |
|FillRectRot         | SrcOver     | Pattern_BI    | 34    | 46    | 86    | 186   | 558   | 1955  |
|FillRoundU          | SrcOver     | Pattern_BI    | 37    | 49    | 67    | 97    | 150   | 386   |
|FillRoundRot        | SrcOver     | Pattern_BI    | 37    | 49    | 82    | 179   | 525   | 1821  |
|FillTriangle        | SrcOver     | Pattern_BI    | 29    | 32    | 38    | 53    | 90    | 188   |
|FillPolyNZi10       | SrcOver     | Pattern_BI    | 39    | 52    | 74    | 119   | 222   | 503   |
|FillPolyEOi10       | SrcOver     | Pattern_BI    | 40    | 52    | 81    | 125   | 236   | 564   |
|FillPolyNZi20       | SrcOver     | Pattern_BI    | 53    | 81    | 126   | 211   | 390   | 822   |
|FillPolyEOi20       | SrcOver     | Pattern_BI    | 52    | 78    | 133   | 237   | 460   | 947   |
|FillPolyNZi40       | SrcOver     | Pattern_BI    | 72    | 116   | 211   | 385   | 751   | 1441  |
|FillPolyEOi40       | SrcOver     | Pattern_BI    | 70    | 117   | 232   | 464   | 935   | 1854  |
|FillWorld           | SrcOver     | Pattern_BI    | 238   | 323   | 440   | 652   | 1097  | 2113  |
|StrokeRectA         | SrcOver     | Pattern_BI    | 29    | 31    | 34    | 43    | 81    | 218   |
|StrokeRectU         | SrcOver     | Pattern_BI    | 30    | 33    | 38    | 54    | 117   | 349   |
|StrokeRectRot       | SrcOver     | Pattern_BI    | 50    | 72    | 118   | 253   | 689   | 2207  |
|StrokeRoundU        | SrcOver     | Pattern_BI    | 54    | 77    | 116   | 159   | 220   | 455   |
|StrokeRoundRot      | SrcOver     | Pattern_BI    | 56    | 78    | 134   | 267   | 671   | 2090  |
|StrokeTriangle      | SrcOver     | Pattern_BI    | 36    | 41    | 50    | 68    | 110   | 226   |
|StrokePoly10        | SrcOver     | Pattern_BI    | 62    | 91    | 135   | 219   | 408   | 816   |
|StrokePoly20        | SrcOver     | Pattern_BI    | 90    | 124   | 220   | 427   | 842   | 1673  |
|StrokePoly40        | SrcOver     | Pattern_BI    | 153   | 195   | 332   | 716   | 1630  | 3452  |
|StrokeWorld         | SrcOver     | Pattern_BI    | 3626  | 3218  | 2945  | 2865  | 3508  | 5306  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Total               | SrcOver     | Pattern_BI    | 4951  | 5018  | 5782  | 7893  | 13895 | 30156 |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+

+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Cairo               | CompOp      | Style         | 8x8   | 16x16 | 32x32 | 64x64 |128x128|256x256|
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|FillRectA           | SrcCopy     | Pattern_BI    | 18    | 18    | 21    | 39    | 80    | 169   |
|FillRectU           | SrcCopy     | Pattern_BI    | 659   | 881   | 927   | 941   | 949   | 1252  |
|FillRectRot         | SrcCopy     | Pattern_BI    | 619   | 860   | 908   | 1063  | 1380  | 3105  |
|FillRoundU          | SrcCopy     | Pattern_BI    | 690   | 943   | 964   | 988   | 996   | 1275  |
|FillRoundRot        | SrcCopy     | Pattern_BI    | 623   | 856   | 911   | 1047  | 1342  | 2994  |
|FillTriangle        | SrcCopy     | Pattern_BI    | 672   | 682   | 760   | 897   | 963   | 1036  |
|FillPolyNZi10       | SrcCopy     | Pattern_BI    | 707   | 730   | 976   | 1010  | 1098  | 1266  |
|FillPolyEOi10       | SrcCopy     | Pattern_BI    | 721   | 745   | 1034  | 1037  | 1111  | 1276  |
|FillPolyNZi20       | SrcCopy     | Pattern_BI    | 746   | 797   | 1066  | 1124  | 1244  | 1492  |
|FillPolyEOi20       | SrcCopy     | Pattern_BI    | 768   | 794   | 1072  | 1136  | 1320  | 1555  |
|FillPolyNZi40       | SrcCopy     | Pattern_BI    | 797   | 872   | 1163  | 1288  | 1557  | 2002  |
|FillPolyEOi40       | SrcCopy     | Pattern_BI    | 814   | 901   | 1189  | 1346  | 1696  | 2212  |
|FillWorld           | SrcCopy     | Pattern_BI    | 1119  | 1433  | 1557  | 1729  | 1962  | 2749  |
|StrokeRectA         | SrcCopy     | Pattern_BI    | 786   | 1066  | 1043  | 1043  | 965   | 1119  |
|StrokeRectU         | SrcCopy     | Pattern_BI    | 759   | 1004  | 1007  | 1021  | 1000  | 1252  |
|StrokeRectRot       | SrcCopy     | Pattern_BI    | 750   | 978   | 1052  | 1232  | 1495  | 2965  |
|StrokeRoundU        | SrcCopy     | Pattern_BI    | 847   | 1111  | 1152  | 1186  | 1120  | 1386  |
|StrokeRoundRot      | SrcCopy     | Pattern_BI    | 791   | 1019  | 1105  | 1318  | 1537  | 2856  |
|StrokeTriangle      | SrcCopy     | Pattern_BI    | 831   | 851   | 949   | 1072  | 1127  | 1155  |
|StrokePoly10        | SrcCopy     | Pattern_BI    | 894   | 1056  | 1169  | 1263  | 1346  | 1508  |
|StrokePoly20        | SrcCopy     | Pattern_BI    | 951   | 1169  | 1260  | 1406  | 1656  | 2120  |
|StrokePoly40        | SrcCopy     | Pattern_BI    | 1115  | 1265  | 1413  | 1689  | 2222  | 3443  |
|StrokeWorld         | SrcCopy     | Pattern_BI    | 5396  | 5012  | 4728  | 4594  | 4919  | 6269  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Total               | SrcCopy     | Pattern_BI    | 22083 | 25053 | 27436 | 29482 | 33098 | 46466 |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+

Blend2d:
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Blend2D ST          | CompOp      | Style         | 8x8   | 16x16 | 32x32 | 64x64 |128x128|256x256|
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|FillRectA           | SrcOver     | Pattern_BI    | 0.7   | 1.0   | 2.0   | 5.2   | 13    | 43    |
|FillRectU           | SrcOver     | Pattern_BI    | 9.3   | 1.6   | 4.1   | 13    | 49    | 190   |
|FillRectRot         | SrcOver     | Pattern_BI    | 8.6   | 8.9   | 19    | 56    | 203   | 744   |
|FillRoundU          | SrcOver     | Pattern_BI    | 23    | 16    | 23    | 38    | 78    | 248   |
|FillRoundRot        | SrcOver     | Pattern_BI    | 13    | 18    | 31    | 68    | 208   | 766   |
|FillTriangle        | SrcOver     | Pattern_BI    | 3.8   | 4.5   | 6.0   | 9.5   | 17    | 40    |
|FillPolyNZi10       | SrcOver     | Pattern_BI    | 8.1   | 10    | 14    | 25    | 50    | 114   |
|FillPolyEOi10       | SrcOver     | Pattern_BI    | 8.0   | 10    | 14    | 25    | 50    | 112   |
|FillPolyNZi20       | SrcOver     | Pattern_BI    | 13    | 17    | 25    | 44    | 88    | 199   |
|FillPolyEOi20       | SrcOver     | Pattern_BI    | 13    | 17    | 25    | 44    | 87    | 192   |
|FillPolyNZi40       | SrcOver     | Pattern_BI    | 24    | 31    | 45    | 81    | 153   | 337   |
|FillPolyEOi40       | SrcOver     | Pattern_BI    | 24    | 31    | 46    | 78    | 151   | 329   |
|FillWorld           | SrcOver     | Pattern_BI    | 277   | 307   | 341   | 415   | 538   | 767   |
|StrokeRectA         | SrcOver     | Pattern_BI    | 5.8   | 6.9   | 9.5   | 14    | 23    | 41    |
|StrokeRectU         | SrcOver     | Pattern_BI    | 5.7   | 6.9   | 9.4   | 17    | 31    | 55    |
|StrokeRectRot       | SrcOver     | Pattern_BI    | 9.1   | 12    | 17    | 30    | 53    | 102   |
|StrokeRoundU        | SrcOver     | Pattern_BI    | 27    | 46    | 54    | 71    | 95    | 105   |
|StrokeRoundRot      | SrcOver     | Pattern_BI    | 29    | 48    | 60    | 87    | 123   | 196   |
|StrokeTriangle      | SrcOver     | Pattern_BI    | 9.1   | 9.6   | 11    | 16    | 25    | 46    |
|StrokePoly10        | SrcOver     | Pattern_BI    | 22    | 24    | 30    | 45    | 76    | 141   |
|StrokePoly20        | SrcOver     | Pattern_BI    | 41    | 44    | 56    | 86    | 143   | 269   |
|StrokePoly40        | SrcOver     | Pattern_BI    | 79    | 83    | 104   | 155   | 265   | 501   |
|StrokeWorld         | SrcOver     | Pattern_BI    | 2625  | 2642  | 2619  | 2529  | 2513  | 2536  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Total               | SrcOver     | Pattern_BI    | 3285  | 3403  | 3577  | 3961  | 5045  | 8084  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+

+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Blend2D ST          | CompOp      | Style         | 8x8   | 16x16 | 32x32 | 64x64 |128x128|256x256|
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|FillRectA           | SrcCopy     | Pattern_BI    | 0.4   | 0.4   | 0.6   | 1.2   | 3.6   | 19    |
|FillRectU           | SrcCopy     | Pattern_BI    | 8.3   | 1.3   | 3.0   | 9.3   | 33    | 127   |
|FillRectRot         | SrcCopy     | Pattern_BI    | 8.1   | 8.1   | 16    | 45    | 148   | 558   |
|FillRoundU          | SrcCopy     | Pattern_BI    | 22    | 15    | 22    | 35    | 63    | 164   |
|FillRoundRot        | SrcCopy     | Pattern_BI    | 13    | 17    | 28    | 58    | 162   | 574   |
|FillTriangle        | SrcCopy     | Pattern_BI    | 3.8   | 4.4   | 6.0   | 9.2   | 16    | 34    |
|FillPolyNZi10       | SrcCopy     | Pattern_BI    | 8.0   | 10    | 14    | 24    | 46    | 100   |
|FillPolyEOi10       | SrcCopy     | Pattern_BI    | 7.9   | 10    | 14    | 24    | 46    | 98    |
|FillPolyNZi20       | SrcCopy     | Pattern_BI    | 13    | 17    | 25    | 43    | 90    | 178   |
|FillPolyEOi20       | SrcCopy     | Pattern_BI    | 13    | 17    | 25    | 43    | 82    | 173   |
|FillPolyNZi40       | SrcCopy     | Pattern_BI    | 24    | 31    | 45    | 76    | 145   | 310   |
|FillPolyEOi40       | SrcCopy     | Pattern_BI    | 24    | 31    | 45    | 75    | 144   | 304   |
|FillWorld           | SrcCopy     | Pattern_BI    | 277   | 301   | 340   | 419   | 529   | 742   |
|StrokeRectA         | SrcCopy     | Pattern_BI    | 5.7   | 6.8   | 8.9   | 13    | 21    | 37    |
|StrokeRectU         | SrcCopy     | Pattern_BI    | 5.6   | 6.7   | 8.9   | 13    | 21    | 38    |
|StrokeRectRot       | SrcCopy     | Pattern_BI    | 9.0   | 11    | 17    | 29    | 52    | 99    |
|StrokeRoundU        | SrcCopy     | Pattern_BI    | 26    | 45    | 54    | 70    | 80    | 97    |
|StrokeRoundRot      | SrcCopy     | Pattern_BI    | 29    | 48    | 59    | 84    | 119   | 186   |
|StrokeTriangle      | SrcCopy     | Pattern_BI    | 9.1   | 9.6   | 11    | 16    | 25    | 44    |
|StrokePoly10        | SrcCopy     | Pattern_BI    | 22    | 24    | 30    | 45    | 74    | 139   |
|StrokePoly20        | SrcCopy     | Pattern_BI    | 41    | 44    | 55    | 82    | 139   | 259   |
|StrokePoly40        | SrcCopy     | Pattern_BI    | 77    | 83    | 105   | 152   | 257   | 489   |
|StrokeWorld         | SrcCopy     | Pattern_BI    | 2619  | 2625  | 2591  | 2533  | 2477  | 2528  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+
|Total               | SrcCopy     | Pattern_BI    | 3272  | 3374  | 3534  | 3906  | 4782  | 7308  |
+--------------------+-------------+---------------+-------+-------+-------+-------+-------+-------+

Blend2d is fastest. I want know why? Cairo with opengl is slower than withtou opengl, why? If add get data from opengl, it will be slower. 
Why do we need to hardware accelate?

Please help me ,thank you.

**Comment by kobalicek** [comment]
Blend2D was designed from scratch to offer the best software-based 2D rendering performance.

I think Cairo being slower even when using hardware acceleration is because of its design. I cannot tell you why exactly, but studying its source code may help you better understand that.

**Comment by miaotianlei** [comment]
> Blend2D was designed from scratch to offer the best software-based 2D rendering performance.
> 
> I think Cairo being slower even when using hardware acceleration is because of its design. I cannot tell you why exactly, but studying its source code may help you better understand the reasons.

Thank your help. I don't read its source code. I open its website, It declares that OpenGL can be used for hardware acceleration， but the test case indicates that it does not conform to its declaration.

I want to know what do I use opengl to do? only draw 3d? 

Thank you!

**Comment by kobalicek** [comment]
I don't think that I can answer that question. OpenGL is a universal API that is widely used for both 2D and 3D.

**Comment by miaotianlei** [comment]
Thank you again.
