### ISSUE TITLE
Image save error

### ISSUE THREAD

**Issue by miaotianlei** [blend2d/blend2d#152]
I have a picture, I use BLImage to load it, then I save to test.png. The file test.png is different with origin image.
Origin image:
![123](https://user-images.githubusercontent.com/18277316/190602282-84338b02-a33d-4bd3-b53c-3a154cb4623a.jpg)

New image after save:
![kk](https://user-images.githubusercontent.com/18277316/190602510-597a1fb9-342e-438f-9c00-2e992f54e531.png)

**Comment by kobalicek** [comment]
Can you provide the original image?

**Comment by miaotianlei** [comment]
> Can you provide the original image? Or it's the JPEG provided? I will take a look

Hi， The source url is http://virtualman.oss-cn-beijing.aliyuncs.com/media_prefabricate/123aef70-9d07-4705-a75e-d90f2649f5f3.jpg, Please download it and test.

**Comment by kobalicek** [comment]
Sorry for waiting too long, I have found the issue, thanks for the bug report and BTW the image is PNG, not JPEG :)

**Comment by miaotianlei** [comment]
Did the bug been fiexed in newest version?
