### ISSUE TITLE
incorrect familyName

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#153]
I'm experiencing some incorrect results with this font-file "Quicksand_Light.otf"
regarding how details are extracted from its NAME table.
The weird thing about this font-file is that its "familyName" is different on Windows/Linux.
On Windows its familyName is "Quicksand Light",
On Linux   its familyName is "Quicksand"
(as reported by the basic font-installator utilities)

When inspected through Blend2d (BLFontFace ...), the resulting familyName is "Quicksand",
independently of the running platform, and this is incoherent at least on Windows.

I've examined the logic used in "opentype/otname.cpp" for selecting the
best record in the NAME table, and I noticed some special heuristic assumptions
such as ".. Prefer TypographicFamilyName over FamilyName and WWSFamilyName..."

My question is:
* is this font-file wrong ? (end of the story).
or
* are the heuristics used in "opentype/otname.cpp" flawed ?

[Quicksand_Light.zip](https://github.com/blend2d/blend2d/files/9641053/Quicksand_Light.zip)

**Comment by kobalicek** [comment]
I would not say it's flawed. I think that Windows has many hacks for backward compatibility and what you are seeing doesn't have to be typographic metrics. It's even possible you would get a different family name in GDI vs DirectWrite in this case.

I'm not saying Blend2D's logic is perfect, but it tries to give you family name that is without styles, whenever possible.

**Comment by kobalicek** [comment]
I'm not sure we should keep this one as open.

Windows text metrics is a huge compatibility issue, that's why the family name is sometimes mixed with styles, which is wrong though. So I think what Blend2D does is right and thus we should not need to do anything in this direction.

Agree?

**Comment by kobalicek** [comment]
I'm closing this one as I think there is not much to be done in this case.

I think that what Blend2D does is the correct behavior, because "Quicksand Light" is not a family name, it's reported by Windows, because historically its API didn't have the ability to express "Light", but only "Bold". However, Blend2D has the ability to express "Light" so it tries to not mix styles with family names, and it does that consistently across platforms.
