### ISSUE TITLE
setStrokeWidth() what unit of measure

### ISSUE THREAD

**Issue by HerryJessica** [blend2d/blend2d#155]
ctx.setStrokeWidth(1.0); I found that this doesn't seem to be a pixel unit, so what unit is it?

**Comment by kobalicek** [comment]
Hello, stroke width is actually a pixel unit.

**Comment by Oldes** [comment]
@HerryJessica maybe it is because you see the line blurred, but that is because you are drawing the 1px line across two pixels.

**Comment by HerryJessica** [comment]
thanks ! indeed pixel units
