### ISSUE TITLE
Assertion failure while stroking `BLPath` with a cubic Bézier

### ISSUE THREAD

**Issue by LuizZak** [blend2d/blend2d#157]
```cpp
BLImage img(500, 500, BL_FORMAT_PRGB32);
BLContext ctx(img, cci);

BLPath path;

path.moveTo(326.9375, 253.8544921875);
path.cubicTo(350.0, 253.8544921875, 326.9375, 253.8544921875, 350.0, 253.8544921875);

ctx.setStrokeStyle(BLRgba32(0xFFFFFFFF));
ctx.strokePath(path);
```

This particular Bézier seems to fail with an assertion:

`[Blend2D] ASSERTION FAILURE: '_zone->ptr<EdgeVector<CoordT>>()->pts == _ptr || _ptr[-1].y <= y' at '[...]/blend2d/raster/../raster/edgebuilder_p.h' [line 2223]`

**Comment by kobalicek** [comment]
The problem is in `dullRoundJoin()` when calculating normal of a vector during stroking. Will investigate further.
