### ISSUE TITLE
Fail to load PNG image

### ISSUE THREAD

**Issue by randomguy76845** [blend2d/blend2d#16]
I got error 65577

**Comment by r00ster91** [comment]
I'm sure it would be helpful if you include code and the image you are trying to load.

**Comment by randomguy76845** [comment]
Just use getting-started-3
and here is PNG version converted by Paint

![texture](https://user-images.githubusercontent.com/49557140/56150280-c093d800-5fd8-11e9-8c9a-3d21c0ab937b.png)

**Comment by kobalicek** [comment]
The decoder is fine, your error is `BL_ERROR_UNKNOWN_SYSTEM_ERROR`, which means that something happened during IO and not decoding. If you put a breakpoint at `blTraceError()` you should know exactly where it failed, maybe that would help you to understand what the error is and to see if there is anything wrong in Blend2D.

**Comment by randomguy76845** [comment]
This is where blTraceError called

```
BL_DEFLATE_FINI(this);
```
at blend2d\codec\bldeflate.cpp(638)

Before that, it came from

```
uint32_t iEnd = blMin<uint32_t>(i + 8, hclen);
BL_DEFLATE_NEED_BITS(iEnd * 3);
```
at blend2d\codec\bldeflate.cpp(458)

i = 8
hclen = 19

dflSize = 31
iEnd = 16

**Comment by kobalicek** [comment]
Ok, I actually found a wrong error as I have added few in my working branch. Your error is indeed `BL_ERROR_INVALID_DATA`. I will check it out although I had no problems loading the file on my machine, so this has to be something 32-bit related

**Comment by randomguy76845** [comment]
You're right. No problem for 64-bit on my machine.

**Comment by kobalicek** [comment]
Ok, I found an issue.

Let me know if e159d1dfa7a2ad2d39b50010aa6cd48d23a134ee fixes the issue.

**Comment by randomguy76845** [comment]
Yes, fixed.
