### ISSUE TITLE
Is it possible to ouput an SVG file from Blend2D?

### ISSUE THREAD

**Issue by GitBruno** [blend2d/blend2d#166]

**Comment by kobalicek** [comment]
No, and this is at the moment not on roadmap.

I would be possible though, as the BLContext has a "virtual table" like interface, so it could be overridden to provide non-raster output like SVG or PDF, but we don't plan to focus on this feature at the moment.

**Comment by kobalicek** [comment]
Closing as this is not on roadmap atm.
