### ISSUE TITLE
crash: blitImage + setTransform

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#176]
Trying to upgrade my app to Blend2d 0.10.1 .. 0.10.2  ..  still serious problems 
// Tested with 0.10.2  and on Fiddle (0.10.1)
   
//  DEMO:   copy a part of an image (WHITE) over a RED image

BLImage render(const BLContextCreateInfo& cci) {ext.
  BLImage img1(200, 200, BL_FORMAT_PRGB32);
  BLContext ctx1(img1, cci);
  ctx1.setFillStyle(BLRgba32(0xFFFF0000)); // RED
  ctx1.fillAll();

  BLImage img2(200, 200, BL_FORMAT_PRGB32);
  BLContext ctx2(img2, cci);
  ctx2.setFillStyle(BLRgba32(0xFFFFFFFF)); // WHITE
  ctx2.fillAll();

  // uncommenting the following setTransform(2x2), 
  // I expected that a white square scaled 2x2 be placed at (6,6)  ... CRASH

 // ctx1.setTransform( { 2, 0, 0, 2, 0, 0} );  // scale 2x2 (*CRASH*)
   //alternative:
 // ctx1.setTransform( { 1, 0, 0, 1, 22, 33 }); // translate (OK) 

  BLRectI fromR = {0,0, 20, 20};
  BLPoint toP = { 3,3 };
  
  BLResult blRes = ctx1.blitImage(toP,img2,fromR);
 
  return img1;
}

**Comment by abu-irrational** [comment]
My apologies:  cut&paste mistake..  Here is the code:

BLImage render(const BLContextCreateInfo& cci) {
  BLImage img1(200, 200, BL_FORMAT_PRGB32);
  BLContext ctx1(img1, cci);

  BLImage img2(200, 200, BL_FORMAT_PRGB32);
  BLContext ctx2(img2, cci);

  ctx1.setFillStyle(BLRgba32(0xFFFF0000)); // RED
  ctx1.fillAll();

  ctx2.setFillStyle(BLRgba32(0xFFFFFFFF)); // WHITE
  ctx2.fillAll();

  // uncommenting the following setTransform(2x2), 
  // I expected that a white square scaled 2x2 be placed at (6,6)  ... CRASH

  //ctx1.setTransform( { 2, 0.0, 0.0, 1.0, 0.0, 0.0} );  // scale 2x2 (*CRASH*)
   //alternative:
  // ctx1.setTransform( { 1, 0, 0, 1, 22, 33 }); // translate (OK) 
blDebugContext(&ctx1);
  BLRectI fromR = {0,0, 20, 20};
  BLPoint toP = { 3,3 };
  
  BLResult blRes = ctx1.blitImage(toP,img2,fromR);
 
  return img1;
}

**Comment by kobalicek** [comment]
Yeah I can confirm that there is some issue, thanks for reporting this one

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/blend2d/blend2d/commit/55ea160c9e8d9a2cd92a90bb229f8ba69eb65d74

**Comment by abu-irrational** [comment]
OK . Fixed
