### ISSUE TITLE
blGradientEquals returning inverted result when implementations arent the same object

### ISSUE THREAD

**Issue by Veykril** [blend2d/blend2d#18]
Found a small error in the the function which gives you the opposite bool result when the implementation pointers arent equal and the stops are equal the function returns true if one of the other fields are unequal and false if they are all equal.
 https://github.com/blend2d/blend2d/blob/df7b257a67b56c7a68fbffb629937e6447a2b0c2/src/blend2d/blgradient.cpp#L980-L994

**Comment by kobalicek** [comment]
Thanks, should be okay now!

**Comment by Veykril** [comment]
Works now, thanks for the quick fix!
