### ISSUE TITLE
Build failure simdx86_test_avx512.cpp, MingGW-w64, static, cmake/ninja, no tests

### ISSUE THREAD

**Issue by squrky** [blend2d/blend2d#192]
Building the contents of `blend2d-0.10.6.tar.xz` on MinGW-w64 with cmake and ninja. 

* Extract tarball to `blend2d` directory
* `cd blend2d`, `mkdir build`, `cd build`
* Configure with `cmake .. -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=true -DBLEND2D_CFLAGS_AVX512=true`

```
-- Building for: Ninja
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test __CxxFlag__fno_enforce_eh_specs
-- Performing Test __CxxFlag__fno_enforce_eh_specs - Success
-- Performing Test __CxxFlag__mllvm___disable_loop_idiom_all
-- Performing Test __CxxFlag__mllvm___disable_loop_idiom_all - Failed
-- Performing Test __CxxFlag__fno_threadsafe_statics
-- Performing Test __CxxFlag__fno_threadsafe_statics - Success
-- Performing Test __CxxFlag__fno_semantic_interposition
-- Performing Test __CxxFlag__fno_semantic_interposition - Success
-- Performing Test __CxxFlag__fmerge_all_constants
-- Performing Test __CxxFlag__fmerge_all_constants - Success
-- Performing Test __CxxFlag__ftree_vectorize
-- Performing Test __CxxFlag__ftree_vectorize - Success
-- Performing Test __CxxFlag__mavx
-- Performing Test __CxxFlag__mavx - Success
-- Performing Test __CxxFlag__mavx2
-- Performing Test __CxxFlag__mavx2 - Success
-- Performing Test __CxxFlag__mavx512bw__mavx512dq__mavx512cd__mavx512vl
-- Performing Test __CxxFlag__mavx512bw__mavx512dq__mavx512cd__mavx512vl - Success
** AsmJit Summary **
   ASMJIT_DIR=C:/dev/blend2d/3rdparty/asmjit
   ASMJIT_TEST=FALSE
   ASMJIT_TARGET_TYPE=EMBED
   ASMJIT_DEPS=
   ASMJIT_LIBS=
   ASMJIT_CFLAGS=-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS=-Wall;-Wextra;-Wconversion;-fno-math-errno;-fno-threadsafe-statics;-fno-semantic-interposition;-DASMJIT_STATIC
   ASMJIT_PRIVATE_CFLAGS_DBG=
   ASMJIT_PRIVATE_CFLAGS_REL=-O2;-fmerge-all-constants;-fno-enforce-eh-specs
** Blend2D Summary **
   BLEND2D_DIR=C:/dev/blend2d
   BLEND2D_TEST=FALSE
   BLEND2D_TARGET_TYPE=STATIC
   BLEND2D_DEPS=
   BLEND2D_LIBS=blend2d
   BLEND2D_CFLAGS=-DBL_STATIC
   BLEND2D_PRIVATE_CFLAGS=-Wall;-Wextra;-fno-exceptions;-fno-rtti;-fno-math-errno;-fno-trapping-math;-fno-finite-math-only;-fno-threadsafe-statics;-fno-semantic-interposition;-DBL_STATIC;-msse2;-DBL_BUILD_OPT_AVX512;-DASMJIT_STATIC;-DASMJIT_NO_STDCXX;-DASMJIT_NO_FOREIGN
   BLEND2D_PRIVATE_CFLAGS_DBG=
   BLEND2D_PRIVATE_CFLAGS_REL=-O2;-fno-enforce-eh-specs;-fmerge-all-constants;-ftree-vectorize
-- Configuring done (4.8s)
-- Generating done (0.2s)
-- Build files have been written to: C:/dev/blend2d/build
```

* Build with `ninja -j16`, produces lots of build warnings etc, but will compile everything successfully, except one test file which fails with the following error:

```
[1/2] Building CXX object CMakeFiles/blend2d.dir/src/blend2d/simd/simdx86_test_avx512.cpp.obj
FAILED: CMakeFiles/blend2d.dir/src/blend2d/simd/simdx86_test_avx512.cpp.obj
C:\msys64\mingw64\bin\c++.exe  -IC:/dev/blend2d/3rdparty/asmjit/src -O3 -DNDEBUG -fvisibility=hidden -Wall -Wextra -fno-exceptions -fno-rtti -fno-math-errno -fno-trapping-math -fno-finite-math-only -fno-threadsafe-statics -fno-semantic-interposition -DBL_STATIC -msse2 -DBL_BUILD_OPT_AVX512 -DASMJIT_STATIC -DASMJIT_NO_STDCXX -DASMJIT_NO_FOREIGN -O2 -fno-enforce-eh-specs -fmerge-all-constants -ftree-vectorize  true -mavx512bw -mavx512dq -mavx512cd -mavx512vl -MD -MT CMakeFiles/blend2d.dir/src/blend2d/simd/simdx86_test_avx512.cpp.obj -MF CMakeFiles\blend2d.dir\src\blend2d\simd\simdx86_test_avx512.cpp.obj.d -o CMakeFiles/blend2d.dir/src/blend2d/simd/simdx86_test_avx512.cpp.obj -c C:/dev/blend2d/src/blend2d/simd/simdx86_test_avx512.cpp
c++.exe: warning: true: linker input file unused because linking not done
c++.exe: error: true: linker input file not found: No such file or directory
ninja: build stopped: subcommand failed.
```

Warnings look like this, just for reference:

```
C:/dev/blend2d/src/blend2d/geometry.h:815:124: warning: 'p[6].BLPoint::y' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/geometry.h:815:124: warning: 'p[6].BLPoint::x' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/geometry.h:819:136: warning: 'p[5].BLPoint::y' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/geometry.h:819:136: warning: 'p[5].BLPoint::x' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/geometry.h:819:136: warning: 'p[4].BLPoint::y' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/geometry.h:819:136: warning: 'p[4].BLPoint::x' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/threading/futex.cpp:42:46: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'BLFutex::FutexWinAPI::WaitOnAddressFunc' {aka 'int (*)(void*, void*, long long unsigned int, unsigned int)'} [-Wcast-function-type]
C:/dev/blend2d/src/blend2d/threading/futex.cpp:43:46: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'BLFutex::FutexWinAPI::WakeByAddressSingleFunc' {aka 'void (*)(void*)'} [-Wcast-function-type]
C:/dev/blend2d/src/blend2d/threading/futex.cpp:44:46: warning: cast between incompatible function types from 'FARPROC' {aka 'long long int (*)()'} to 'BLFutex::FutexWinAPI::WakeByAddressAllFunc' {aka 'void (*)(void*)'} [-Wcast-function-type]
C:/dev/blend2d/src/blend2d/raster/analyticrasterizer_p.h:1252:9: warning: ignoring loop annotation
C:/dev/blend2d/src/blend2d/raster/analyticrasterizer_p.h:1252:9: warning: ignoring loop annotation
C:/dev/blend2d/src/blend2d/raster/analyticrasterizer_p.h:1252:9: warning: ignoring loop annotation
C:/dev/blend2d/src/blend2d/raster/analyticrasterizer_p.h:1252:9: warning: ignoring loop annotation
C:/dev/blend2d/src/blend2d/raster/rastercontext.cpp:4029:10: warning: 'dstBox.BLBoxI::y1' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/raster/rastercontext.cpp:4029:10: warning: 'dstBox.BLBoxI::x1' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/raster/rastercontext.cpp:4029:10: warning: 'dstBox.BLBoxI::y0' may be used uninitialized [-Wmaybe-uninitialized]
C:/dev/blend2d/src/blend2d/raster/rastercontext.cpp:4029:10: warning: 'dstBox.BLBoxI::x0' may be used uninitialized [-Wmaybe-uninitialized]
```

I found two workarounds for this build failure that seem to work for me:

1. Omit `-DBLEND2D_CFLAGS_AVX512=true` when configuring, AVX is detected regardless, or:
2. Comment out `blend2d/simd/simdx86_test_avx512.cpp` like so:

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index ea49ca0..ef99929 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -711,7 +711,7 @@ set(BLEND2D_SRC_LIST
   blend2d/simd/simdx86_p.h
   blend2d/simd/simdx86_test_avx.cpp
   blend2d/simd/simdx86_test_avx2.cpp
-  blend2d/simd/simdx86_test_avx512.cpp
+  # blend2d/simd/simdx86_test_avx512.cpp
   blend2d/simd/simdx86_test_sse2.cpp
   blend2d/simd/simdx86_test_sse4_1.cpp
   blend2d/simd/simdx86_test_sse4_2.cpp
```

Note: I am not supplying `-DBLEND2D_TEST=true` to cmake. 

Besides this, the static library seems to build and function correctly under MinGW-w64. 

Thanks.

**Comment by kobalicek** [comment]
Thanks for this report!

I think this is not about the file, but it's about the flags, from the command line:

```-ftree-vectorize  true -mavx512bw```

I think this is caused by running cmake with:

```
 -DBLEND2D_CFLAGS_AVX512=true
```

`BLEND2D_CFLAGS_AVX512` cannot actually be a boolean value, it's internally set to contain compiler flags that enable AVX-512 compilation. You should not need to set that manually.

If you want to force Blend2D to be built with AVX-512 flags by default (which would imply it would not be able to run on machines without AVX-512), you would have to use the actual flags, like:

```
cmake <options> -DCMAKE_CXX_FLAGS=-mavx512vl
```

Can you retry?

**Comment by squrky** [comment]
Ah yes, I see my mistake. For the benefit of people skimming this issue, the following error message was confusing (to me):

```
c++.exe: warning: true: linker input file unused because linking not done
```

The "true" in this error, as you pointed out @kobalicek, is relating to the bad cmake argument `-DBLEND2D_CFLAGS_AVX512=true` making it all the way to the build line.

The build works perfectly fine without this flag 👍. My initial motivation was to ensure that we get all the nice SIMD/AVX codepaths when compiling under MinGW-w64, and I wasn't sure if that would be the case by default. Looking again at `CMakeLists.txt` it seems that you have dedicated logic for this in the fallback case when the compiler _isn't_ MSVC. 

MinGW-w64 support is vital for people like me who want to build their projects for Windows, Linux (and Mac) while also targetting a single compiler like GCC or Clang. Targetting GCC/Clang as well as MSVC in a single codebase leads to some highly unpleasant workaraounds for the differences in C++ dialect supported by each compiler. Would you be persuaded to explicitly support MinGW-w64, and to make a note to this effect in your build instructions?

Thanks for this epic library, I'm looking forward to really getting stuck in!

**Comment by kobalicek** [comment]
@squrky The build system has two cases - MSVC and GCC/Clang, but there is no preference in terms of which compiler to use (I prefer clang, but you can use any of GCC, clang, and MSVC). So GCC should be perfectly fine across platforms and you should get all the optimizations that Blend2D provides with GCC. In your case the flags detection works:

```
-- Performing Test __CxxFlag__mavx
-- Performing Test __CxxFlag__mavx - Success
-- Performing Test __CxxFlag__mavx2
-- Performing Test __CxxFlag__mavx2 - Success
-- Performing Test __CxxFlag__mavx512bw__mavx512dq__mavx512cd__mavx512vl
-- Performing Test __CxxFlag__mavx512bw__mavx512dq__mavx512cd__mavx512vl - Success
```

These will be used by SIMD accelerated functions, but these only affect C++ code. JIT always uses the best extensions, so even if C++ code is not compiled with AVX-512 support, JIT will still use it if detected.

So, this leads to my question - what is currently not supported when using MinGW? Or maybe, what do you think should be added to build instructions?

I agree that when compiling with GCC there is a bunch of warnings that I don't like. In master branch I have disabled loop annotations when compiling with GCC so you won't get the "warning: ignoring loop annotation" (this warning for some reason cannot be just turned off). The other warnings look like GCC has a problem in diagnostics in this case as the code is not using uninitialized values (and clang doesn't report these).

I think the best would be to add MINGW to CI, but I didn't want to spend much time on that myself.

**Comment by squrky** [comment]
> So, this leads to my question - what is currently not supported when using MinGW? Or maybe, what do you think should be added to build instructions?

I have a better understanding of how the build logic works now: You lump MinGW in with any other Clang/GCC platform and thus it should work without any special handling. That sounds like the right approach 👍. It wasn't totally clear from the build instructions when SIMD/AVX acceleration would be compiled in, I assumed (incorrectly) that I would need to explicitly enable those so that I would get the best possible performance out of the box. Thanks for clarifying. 

> I agree that when compiling with GCC there is a bunch of warnings that I don't like

This was just for reference, I didn't see anything nasty in the code.

> I think the best would be to add MINGW to CI, but I didn't want to spend much time on that myself.

Totally fair. I have no idea what that entails, maybe someone will come along and submit a PR for that, maybe I will one day 🤷 

I'm taking the liberty to close this issue because you have completely explained the problem I was having. Thanks again.
