### ISSUE TITLE
Crash on  blitImage with different image format

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#196]
Trying to copy BLImages (with different format) among different BLcontexts, causes a crash.
Here's a minimal fiddle.

// ========================================
BLImage render(const BLContextCreateInfo& cci) {
  
  BLImage img0(400, 400, BL_FORMAT_A8);
  BLImage img1(400, 400, BL_FORMAT_XRGB32);
  // ... initialize img0 and img1

   // copy img1 (RGB) -> img0 (A8)    **OK**
  BLContext ctx0(img0);
    ctx0.blitImage(BLPointI(0,0),img1);
  
   // copy img0 (A8) -> img1 (RGB)     **CRASH**
  BLContext ctx1(img1);
    ctx1.blitImage(BLPointI(0,0),img0);
  
  return img1;
}

I have another crash test, but it's difficult to reproduce  ...
Surprisingly it's the opposite of the above test case, i.e.  blitting a XRGB32 image over an A8 image ... 
I'm using the master branch (10-march-2024) and when I try to blit a XRGB32 image in a context with an attached A8 image, I get the following warning
   bl::Pipeline::JIT assembling error: InvalidInstruction: vpackuswb xmm@255, <None>
   Blend2D error 0x10002 INVALID_STATE

**Comment by abu-irrational** [comment]
Just a correction:
 What I'm trying to do is working with PRGB32 images (not XRGB32 images) and A8 images.
You should then correct the above fiddle script.   Anyway, the result is the same.

**Comment by kobalicek** [comment]
I checked it out and this is indeed a bug.

This needs a fix and a test case so it won't happen again.

Thanks for the report!

**Comment by kobalicek** [comment]
Update: This will be fixed once aarch64_jit branch is merged.

**Comment by kobalicek** [comment]
Fixed in v0.11.0 - thanks for the report!
