### ISSUE TITLE
close() on path doesn't interact with stroking as expected.

### ISSUE THREAD

**Issue by smcallis** [blend2d/blend2d#201]
The close() command on BLPath says that it works like the 'Z' command in SVG and links [here](https://www.w3.org/TR/SVG/paths.html#PathDataClosePathCommand).   Which indicates that stroking a closed path should join back to the start of the curve.   But if I don't manually do a lineTo back to the start, my strokes don't paint fully, which you can see here:

![image](https://github.com/blend2d/blend2d/assets/804394/569ab62b-7211-4a32-911c-b8c4fbf276a0)

**Comment by kobalicek** [comment]
Interesting. I couldn't observe this behavior, so I think this would need a snippet that can reproduce it.

For example this fiddle snippet produces the correct output:

```c++
BLImage render(const BLContextCreateInfo& cci) {
  BLImage img(500, 500, BL_FORMAT_PRGB32);
  BLContext ctx(img, cci);

  ctx.clearAll();

  BLPath p;
  p.moveTo(200, 100);
  p.lineTo(300, 200);
  p.lineTo(100, 200);
  p.close();

  p.moveTo(200, 300);
  p.lineTo(300, 400);
  p.lineTo(100, 400);
  p.close();

  ctx.strokePath(p, BLRgba32(0xFFFFFFFF));

  return img;
}
```

**Comment by smcallis** [comment]
I'll see if I can get a snippet to reproduce today.

**Comment by smcallis** [comment]
I haven't been able to reproduce this so I think it must have been on my end, though I'm not sure exactly how.  I'll refile if I come across a reproduction.
