### ISSUE TITLE
how to do offscreen rendering in qt?

### ISSUE THREAD

**Issue by evehal** [blend2d/blend2d#202]
https://stackoverflow.com/questions/31323749/easiest-way-for-offscreen-rendering-with-qopenglwidget

in qt, i can do that with fbo, how to use blend2d with fbo?

**Comment by kobalicek** [comment]
Blend2D always renders to pixel buffers, thus it's always offscreen.

You either let Blend2D allocate that buffer by creating a BLImage or you have your own and use `BLImage::createFromData()` - see https://blend2d.com/doc for a reference documentation.

BTW you can also wrap QImage to BLImage and render to it, etc... This is done by Blend2D demos that compare Blend2D and Qt rendering.

**Comment by evehal** [comment]
Thank you kobalicek
Im developing a real time mixing(A/B textures) application like vMix
I guess I can use blend2d instead of qt qpainter for drawing titles, 2d fx, images ...
So how to get fbo or offscreen texture id(opengl),and does blend2d work in non-main thread(QT UI Thread)?

**Comment by evehal** [comment]
Thank you kobalicek

**Comment by openlearnc** [comment]
@kobalicek Did you considered adding the gpu backend.When drawing with blend2d, in real-time scenes, the entire canvas must be cleaned each frame, of course, or just multiple rectangular areas can be cleaned, but this needs to calculate the aabb of the graph. In real-time rendering of the scene, the use of hardware acceleration is necessary.

**Comment by openlearnc** [comment]
Nanovg is a use opengl apis for hardware rendering library, here is a simple way of allowing blend2d support hardware acceleration, by putting some blend2d draw instruction to nanovg apis, such as moveto, lineto, quadto, bezierto.nanovg does not cache path control points, but uses them directly, blend2d caches path control points，The advantage of this is that blend2d supports hardware acceleration while also can use existing apis, such as hittest.

**Comment by kobalicek** [comment]
A the moment the features implemented are driven by spare time of Blend2D authors. The goal is to only start working on anything GPU related when everything CPU related is in excellent shape and fully optimized. Thus, I don't see GPU support in near time, it's more like a vision of the project at the moment.

**Comment by openlearnc** [comment]
https://github.com/styluslabs/ulib/blob/master/painter.cpp,here's a reference.
