### ISSUE TITLE
BLImage::readFromFile("d:/checkbox.png")  ERROR BL_ERROR_INVALID_DATA,    //!< Invalid or corrupted data.

### ISSUE THREAD

**Issue by qd1308504206** [blend2d/blend2d#204]
```cpp
  {
    BLImage img;
    BLResult ret = img.readFromFile("d:/checkbox.png");
    //ret = BL_ERROR_INVALID_DATA,                 //!< Invalid or corrupted data.
    //ret = 65582
    int w = img.width();
    int h = img.height();
    std::cout << "w:" << w << ", h:" << h << std::endl;
  }
```
please download and unzip the file 【demoPng.zip 】
[demoPng.zip](https://github.com/user-attachments/files/15983714/demoPng.zip)

win 10
debug64
visual studio 2022
blend2d version 0.11.1

**Comment by kobalicek** [comment]
I will look into it in the evening. The PNG is valid.

**Comment by kobalicek** [comment]
Fixed by https://github.com/blend2d/blend2d/commit/a9e8f4063470e906802c171ef53cade60e7070be
