### ISSUE TITLE
Weird Issue with makeMutable and pixelData

### ISSUE THREAD

**Issue by calvinsomething** [blend2d/blend2d#210]
I wrote a function for turning a PRGB32 formatted `BLImage` to an A8 mask. I thought it was working but the output was very distorted for certain image sizes... I assumed if I created a new image with the same dimensions as the source image, and just converted each pixel from 32 bits to 8 bits it should have a similar looking output. But here are some results:

Original PNG (379w * 373h):
![mushroom](https://github.com/user-attachments/assets/afc0d27d-31f1-49a4-b038-0a67e79f54bd)

A8 output at original size:
![out](https://github.com/user-attachments/assets/2526f3ee-6015-49d4-8a98-9faab5ee082d)

A8 resized arbitrarily until it worked (416w * 410w):
![out2](https://github.com/user-attachments/assets/8c1a8dc3-9f8f-47a0-bf6a-13f8c6414dbd)

Here is the example code:
```
    const uint32_t ALPHA = ~(uint32_t)0 << 24;
    const uint32_t RED = ALPHA >> 8;
    const uint32_t GREEN = RED >> 8;
    const uint32_t BLUE = GREEN >> 8;

//  Use original size
    // BLImage image;
    // image.readFromFile(src_file_name);
// Or scale 
    // BLImage src;
    // src.readFromFile(src_file_name);

    // BLImage image(src.width() * 1.1, src.height() * 1.1, BL_FORMAT_PRGB32);
    // BLImage::scale(image, src, BLSizeI{image.width(), image.height()}, BL_IMAGE_SCALE_FILTER_NEAREST);
//

    BLImage mask(image.width(), image.height(), BL_FORMAT_A8);

    BLImageData mask_data;
    mask.makeMutable(&mask_data);

    BLImageData image_data;
    image.getData(&image_data);

    unsigned size = image_data.size.w * image_data.size.h;

    for (int i = 0; i < size; i++)
    {
        uint32_t px = *(static_cast<uint32_t *>(image_data.pixelData) + i);
        uint8_t &mask_px = *(static_cast<uint8_t *>(mask_data.pixelData) + i);
        mask_px = px & BLUE;
    }

    mask.writeToFile(dst_file_name);
```

Different sizes result in different amounts of distortion, and it seems the width is the only thing that matters.

Is there some trick to getting the pixels to map that I don't know?

**Comment by kobalicek** [comment]
The problem is that you are not using the `stride` - Blend2D's image data allocator may align the rows and also image data could be a subimage of a larger image, so it's essential to always use stride when accessing image rows.

Basically:

```
y * stride = image size
y * x != image size
```

Each row starts at `y * stride`

So, to access pixels you should do:

```c++
BLImageData data = ...;

for (uint32_t y = 0; y < uint32_t(data.size.h); y++) {
  uint8_t* pixelData = data.pixelData + y * data.stride;
  for (uint32_t x = 0; x < uint32_t(data.size.w); x++) {
    // access pixelData, of course depending on pixel format
  }
}

```

**Comment by calvinsomething** [comment]
Thank you very much for the immediate reply!

**Comment by kobalicek** [comment]
One interesting detail that is not used by Blend2D itself, but users can do when creating images from external data is also that the stride can be negative, if for some reason the pixels are stored bottom to top - as I said, not used by Blend2D, but that's why stride is `intptr_t`, thus signed.
