### ISSUE TITLE
[Portable Pipeline] blitImage produces garbage

### ISSUE THREAD

**Issue by christianbrugger** [blend2d/blend2d#212]
In [LogikSim](https://github.com/christianbrugger/logiksim/) I am using Blend2D's portable pipeline for memory and thread sanitized builds. This is because the JIT is not supported for these sanitizers, as far as I understand.

I found some render mismatches specifically when using selections. Unlike the rest of the render, selections are drawn in a separate layer and then alpha blended. Here is how it shows up in the application:

![no_jit](https://github.com/user-attachments/assets/e675c0e4-8b80-480d-9f33-1b376844c3ea)
![jit](https://github.com/user-attachments/assets/fc2d4f99-4c4f-4fff-85ad-855b88431383)

I isolated the issue and and think it is related to the `BLContext::blitImage` when using threads. Here is the [fiddle](https://fiddle.blend2d.com/):
```c++
BLImage render(const BLContextCreateInfo& cci) {

  auto info = cci;
  info.threadCount = 1;  // DOES WORK FOR threadCount == 0

  BLImage image(400, 300, BL_FORMAT_PRGB32);
  BLImage layer(400, 300, BL_FORMAT_PRGB32);

  {
      BLContext ctx(layer, info);
      
      // render layer = two blue rounded rects
      ctx.clearAll();
      ctx.setCompOp(BL_COMP_OP_SRC_COPY);
      const auto color = BLRgba32 {0, 128, 255, 96};
      ctx.fillRoundRect(BLRoundRect {81, 81, 55, 55, 5}, color);
      ctx.fillRoundRect(BLRoundRect {171, 81, 55, 55, 5}, color);

      ctx.end();
  }

  {
      BLContext ctx(image, info);
      constexpr auto blend_rect = BLRectI {79, 79, 149, 59};

      // main background = gray box on white background showing blended area
      ctx.fillAll(BLRgba32 {255, 255, 255, 255});
      ctx.fillRect(blend_rect, BLRgba32 {230, 230, 230, 255});

      // blend layer = alpha blending
      ctx.setCompOp(BL_COMP_OP_SRC_OVER);
      ctx.blitImage(blend_rect, layer, blend_rect);

      ctx.end();
  }

  return image;
}
```
These are the results:
![fiddle_no_jit_2](https://github.com/user-attachments/assets/c5947575-4e3c-4838-865a-e9d37fd01574)
![fiddle_jit_2](https://github.com/user-attachments/assets/51749ff1-2ad0-482d-85b7-12b14dc96db3)

The mismatch is not as severe as in the real application, but shows the similar artifacts.

I looked at Issue #182 which noted that composition modes other than `SRC_COPY` and `SRC_OVER` are not supported. The above uses `SRC_COPY`.

I also found that fiddle `Composition.BlitImage` and `Composition.Logo` also show render differences when using threads and `SRC_COPY` or `SRC_OVER`

```c++
BLImage render(const BLContextCreateInfo& cci) {
  auto info = cci;
  info.threadCount = 1;  // DOES WORK FOR threadCount == 0

  BLImage img(256, 256, BL_FORMAT_PRGB32);
  BLContext ctx(img, info);

  ctx.clearAll();

  BLImage tex[2];
  tex[0].readFromFile("textures/tex16.jpg");
  tex[1].readFromFile("textures/tex24.jpg");

  ctx.setCompOp(BL_COMP_OP_SRC_COPY);
  ctx.blitImage(BLPointI(0, 0), tex[0], BLRectI(0, 0, 160, 160));
  ctx.setCompOp(BL_COMP_OP_SRC_COPY);  // SAME FOR BL_COMP_OP_SRC_OVER
  ctx.blitImage(BLPointI(96, 96), tex[1], BLRectI(0, 0, 160, 160));

  return img;
}
```

Issue #182 mentions that the feature set is different for the portable pipeline. As I am now somehow relying on it, more clarity on the current expected support would be very helpful, regarding the different JIT and Non-JIT implementations. So far I naively assumed they are all the same. 

For now I am disabling the render threads for my sanitizer builds that require the portable pipeline.

**Comment by kobalicek** [comment]
Thanks for such a detailed bug report!

I have checked it out and finally spotted the issue. Interestingly, no test found this one.

I think the following commit should fix this:

   - https://github.com/blend2d/blend2d/commit/ca5403c1d02b2bc9d2de581e4cb13e5e80f33860

**Comment by christianbrugger** [comment]
Thank you for the almost instant fix.

Using the new changes my render problems above are gone.

With that I am closing the issue.
