### ISSUE TITLE
Build error MSVC 19.16.27030.1

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#22]
Visual Studio 15 2017
CMake creates project and all that.
ultimately cl compiler will report error:
D8016: '/Ox' and '/RTC1' command-line options are incompatible.
I'm compiling for 32-bit also.  Last time around I just went into the project and disabled either or both of these and moved along, but I think it's worth reporting if you want to fix this at the source.

**Comment by Wiladams** [comment]
More clarity, this applies to 'debug' builds.  When I build for release it's fine as the RTC1 flag is not part of the configuration.  This is true whether from cmake --build . , or from within visual studio (same project files either way).  I'm thinking the proper fix, and what I did in my environment, is to remove the /Ox flag from the debug configuration because it's counter to the runtime checking flag anyway.

**Comment by kobalicek** [comment]
I heard about this although this never happened to me. May I ask how the project was created? Because when using MSVC generator I think you should not explicitly set `CMAKE_BUILD_TYPE` (should be empty) otherwise it would mess with other build options that you can set through IDE.

**Comment by Wiladams** [comment]
following the instructions here: https://blend2d.com/download.html

If course, you do explicitly say to leave the thing blank, instead of setting it, but who reads docs completely anyway.  I just figured I'd try what the instructions say explicitly and see what happens.  So, this is the only issue as far as I can tell.

**Comment by kobalicek** [comment]
Not sure how to fix this, any ideas?

**Comment by Wiladams** [comment]
I'll have to dig into the cmake cruft.  Fairly low priority as the workaround is fairly easy.

**Comment by kobalicek** [comment]
I think this should be fixed. I switched to cmake generator expressions and it automatically fixed this problem. Can you verify it?

**Comment by Wiladams** [comment]
Yah, verified on my last build.  Thanks.
