### ISSUE TITLE
Link error occurred in vs2022 console project compilation.

### ISSUE THREAD

**Issue by xvch666** [blend2d/blend2d#220]
I followed the steps in [Build Instructions](https://blend2d.com/doc/build-instructions.html) and got the `blend2d.lib` file:

```bash
mkdir blend2d-project
cd blend2d-project

git clone https://github.com/blend2d/blend2d
git clone https://github.com/asmjit/asmjit blend2d/3rdparty/asmjit

mkdir blend2d/build
cd blend2d/build

cmake .. -DCMAKE_BUILD_TYPE=Release -DBLEND2D_STATIC=TRUE -DBLEND2D_NO_INSTALL=TRUE
cmake --build . --config Release
```

Next, I use VS2022 to create a console application project (name: ConsoleApp) and make the following settings:

- set `ConsoleApp Properties > Linker > General > Additional Library Directories` to `{blend2d-project path}\blend2d\build\Release`
- set `ConsoleApp Properties > Linker > Input > Additional Dependencies` to `blend2d.lib`
- set `ConsoleApp Properties > C/C++ > General > Additional Include Directories` to `{blend2d-project path}\blend2d\src`

Next, Write the following code in `ConsoleApp.cpp`:

```c++
#include <blend2d.h>

int main()
{
	BLImage img(480, 480, BL_FORMAT_PRGB32);
}
```

When I build this project, I get multiple link errors:

```
error LNK2001: unresolved external symbol __imp__blImageInitAs
error LNK2001: unresolved external symbol __imp__blImageDestroy

fatal error LNK1120: 2 unresolved externals
```

**Comment by kobalicek** [comment]
Maybe it's not easy to find, but it's there documenting `BLEND2D_STATIC`:

  - https://blend2d.com/doc/build-instructions.html

Extracted (`BLEND2D_STATIC` option):

Whether to build Blend2D statically:
  * This would create a static library blend2d and provide `blend2d::blend2d` target that you can link to
  * When enabled `BL_STATIC` is defined during the build and must be defined as well by any code that includes Blend2D. If you use `blend2d::blend2d` target then you don't have to worry about anything as all the necessary stuff would be deduced from using the target

**Comment by xvch666** [comment]
Oh my God I forgot to add BL_STATIC. Thank you for reminding me. Thank you ~

**Comment by xvch666** [comment]
Oh, my God~

I forgot to add `BL_STATIC`. 

Thank you for reminding me. Thank you ~
