### ISSUE TITLE
Member function `BLContext::strokeArc` missing

### ISSUE THREAD

**Issue by christianbrugger** [blend2d/blend2d#223]
In commit [[ci] Documentation and CI update](https://github.com/blend2d/blend2d/commit/fc827d56fb529cb6977d923733dcb411c172cd03) the function `BLContext::strokeArc` was deleted.

I assume this was simply an oversight, as adding this function back manually works just fine.

![image](https://github.com/user-attachments/assets/a3add668-947e-460b-8f05-71e73a9b9b5b)

**Comment by kobalicek** [comment]
Fixed by 16088c4ffb41813d9f0511fb2a6896f5608a4706
