### ISSUE TITLE
fonts need to be opened in shared read mode

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#23]
While trying to use fonts from the windows\fonts\*.ttf files, some of them allow opening, and some do not.  It is typically the ones in use by the system that don't allow opening (Calibri, times, cour, etc).

Reading the fontloader, I see they are opened in READ mode, not READ_SHARE.  Doing separate testing, trying to open files using BLFile shows there is an error in trying to open in shared mode: 32, ERROR_SHARING_VIOLATION, which is ultimately reported as: BL_ERROR_FILE_NAME_TOO_LONG?

At any rate, since I can not control the read flags on the 'createFromFile' calls of BLFont or BLFontLoader, I'm kinda stuck on reading these font files.  It may turn out that the system won't allow for shared reading of these particular font files, which would be a bug in Windows, but I'm thinking it should work.

I don't know what the situation would be in Linux

**Comment by Wiladams** [comment]
That rework seems to have done the trick.  Now I can open the files, and thus, more font files in the system are available to play with.

As a future improvement, it will probably be worthwhile to use memory mapped files so you don't have to waste time creating and freeing buffers.  But, in Windows, it's a multi-step process, so it can definitely wait til some future time.  A full blown font manager could be an add-on, which can deal with all sorts of fonts, and just marshal into the blend2d expected formats for inclusion.

**Comment by kobalicek** [comment]
Memory mapping is there as a part of internal API, however, before alpha/beta I have removed the use of it by default (but kept the impl as I have the same plan). I think adding flags to the loader to use memory mapping would be a good addition.

**Comment by kobalicek** [comment]
BTW I will address the memory mapped data very soon, I have already most of the work done in my local branch.
