### ISSUE TITLE
building apps with blend2d

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#26]
This is not an issue, more like a progress report.
![winman](https://user-images.githubusercontent.com/457634/57053770-f2e23e00-6c44-11e9-8fba-2b397249e697.png)

Assuming the image I just dragged in is visible, I'm essentially creating a "desktop" environment completely from the ground up using blend2d (LuaJIT binding) as the 2D graphics engine.  The only thing used in the host environment is getting a basic window up on the screen (win32) and doing a blit from my 'framebuffer' to the host window.

Lots of fun tidbits in there from having a nice 'WinMan' compositor, to translucent 'windows', multiple BLContext objects interacting on their own individual BLImage backends, a DrawingContext thing that wraps up BLContext, and provides a 'Processing' like interface to boot.

I've taken the original 'getting-started' examples, and turned them into 'graphics', which can be rendered anywhere, any size in a 'window'.  This nicely shows off the scaling capabilities, and highlights any challenges thereof.

I'll be adding keyboard/mouse interaction, but that has more to do with the environment than the graphics themselves, other than testing out Path 'include'.  So, great fun, great exercise of the APIs.  

The fundamental binding to blend2d hasn't changed much since I first did it, so the C API is pretty decent from that perspective.  I haven't tried every feature, such as the move, assign, sort of stuff, but I simply haven't figured out the relevance of those APIs in my garbage collected environment.

So, progress is being made.

I don't know where else I could post this progress report, so I put it here for discussion.

**Comment by Wiladams** [comment]
Also of note, at the top of the image there's a live framerate and mouse positioning tracker.  I have the framerate set at 15, and it's reporting a rate of 12.29.  That's due to inaccuracy of the framerate tracking, not an indication of how slow things are.  The raw framerate can be much higher (blit to host at 120fps), and the drawing will consume some time per frame, but it's nowhere near saturation at this point.

Also, that spirograph thing isn't a static image, it's constantly updating animation, just like the framerate tracker.

The checkerbox pattern is the default background of my 'desktop'.
The 'windows' are the big translucent gray that has the getting started examples, and the smaller one to the right that houses the spirograph.  Just testing the compositor.  Windows can have any background they like, and can have any shape they like, just like with Win32, but all with Blend2d.

The setup for that screen looks like this in code:
```lua
local winman = require("WinMan")

local stopviews = require("STOP_views")
local spiroapp = require("STOP_spiroapp")
local framestatapp = require("STOP_framestat")

local function startup()
    spawn(framestatapp, {x=0, y=0, width=1920, height=20})
    spawn(stopviews,{x=100, y=100, width=1024, height=768})
    spawn(spiroapp,{x=800, y=300, width=640, height=480})
end

winman {width = 1920, height=1080, startup = startup}
```

And the spiroapp looks like

```lua
local SpiroGraphic = require("SpiroGraphic")

local function app(params)
    local win1 = WMCreateWindow(params.x,params.y, params.width, params.height)

    local spg = SpiroGraphic:new({width = params.width, height=params.height})

    win1:add(spg)
    win1:show()

    while true do
        win1:draw()
        yield();
    end
end

return app
```

And the spirographic itself looks like

```lua
local Graphic = require("Graphic")

local floor = math.floor
local random = math.random
local sin = math.sin;
local cos = math.cos

local SpiroGraphic = Graphic:new()

function SpiroGraphic.new(self, obj)
    obj = obj or {}
    
    obj.N = 36;
    obj.theta = 3.14159 * 2 / obj.N;
    obj.centerX = obj.centerX or obj.width/2;
    obj.centerY = obj.centerY or obj.height/2;

    setmetatable(obj, self)
    self.__index = self;
    
    return obj;
end


function SpiroGraphic:draw(ctxt)
    ctxt:stroke(255, 0,0)
    ctxt:setStrokeWidth(1)
    local x = 0;
    local y = 0;


	local Radius = (self.height / 2) - 5;

    for p = 0, self.N-1 do
		local num = floor((p / self.N) * 254.0);
        local r = random(0, num);
		local g = random(0, num);
		local b = random(0, num);
        ctxt:stroke(r, g, b)

		for q = 0, p-1 do
		    ctxt:line(floor(self.centerX + Radius * sin(p * self.theta)), floor(self.centerY + Radius * cos(p * self.theta)),
		     floor(self.centerX + Radius * sin(q * self.theta)), floor(self.centerY + Radius * cos(q * self.theta)));
        end
    end
end

return SpiroGraphic
```

The environment these things live in already contains a little user mode scheduler "scheduler.lua" if you look at the source code.  That gives things like 'spawn', 'periodic', 'on', 'whenever', etc.  That makes it real easy to stitch together task like things.  Interweave with graphics, and there you have it.

**Comment by Wiladams** [comment]
And, I guess it would be nice if the rest of the examples on the home page were available in code.  I can roughly figure out how to replicate them, but it would be nice to have access to the officials used.

**Comment by kobalicek** [comment]
Nice thank you for sharing :)

**Comment by Wiladams** [comment]
Closed as commentary
