### ISSUE TITLE
How are path line options specified

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#27]
I suspect it's related to the BLPathOptionsCore, but I'm not sure how to specify "on the line", "outside", or "inside".  So, when I've got a thickness beyond 1 unit, which way will things be drawn?  Is it controllable (I hope so).

**Comment by yzrmn** [comment]
I suspect you are talking about `BLStrokeOptionsCore`, right? Strokes are drawn half-width to both sides. E.g. if you have width set to `1` it will draw `0.5` to the "left" of the path and `0.5` to the "right".
Currently, there are no other modes to change this behavior. But I think it would be quite easy to do something like `0.2` to the left and `0.8` to the right. However, this might be an issue of how to specify it properly (API design)...

**Comment by Wiladams** [comment]
https://docs.microsoft.com/en-us/windows/desktop/gdiplus/-gdiplus-setting-pen-width-and-alignment-use

Basically pen alignment.  Three options; inset, centered, outside.  Dont need floating control, just these three.  It will make ui precision possible.

**Comment by yzrmn** [comment]
Well, it's not as easy as that. SVG had the `stroke-alignment` property in previous drafts which reflects the settings of GDI+ pens. According to [this](https://svgwg.org/specs/strokes/#SpecifyingStrokeAlignment) there are issues for both open and closed paths. The property is likely removed from SVG 2 because of those.

It would be much easier to just specify left and right widths and not deal with inside/outside orientation. At least up until SVG agrees on how to do it.

**Comment by kobalicek** [comment]
Yes that's true, I think Center/Left/Right options would make sense, but Inset/Outset would be complicated

**Comment by Wiladams** [comment]
I'll admit I've oversimplified.  simple enclosed shapes have an easier 'inside'-'outside'.  Generalized polygons at least have winding order, where you could be using left and right, but may run into Klein bottle problems.  If 'left' and 'right' have an easier time of establishment, then maybe that's the way to go.

For my purposes, it's going to be rect, roundrect that I'm most concerned with, and can easily compensate for by readjusting coordinates, but a generalized solution would be great.  A 'correct' solution would be even greater as it will make logical sense and have fewer hidden corner bugs.

**Comment by Wiladams** [comment]
I'll  close this for now and see if path Booleans change the conversation in the future.  It seems the answer for the forseeable future will be to mind my strokes.  Very challenging with complex paths, but easier for the ones I'm likely to need in the near term.
