### ISSUE TITLE
How To: Applying gradient per object

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#28]
![keyboard](https://user-images.githubusercontent.com/457634/57187312-58cb0180-6ea1-11e9-8631-bdb0a3e70b07.PNG)
I have this keyboard graphic that I've constructed in blend2d.  I want to apply a gradient per key.

```lua
    obj.linear = Gradient.LinearGradient({
        values = {0, 0, 0, self.unit};
        stops = {
          {offset = 0, uint32 = 0xFFFFFFFF},
          {offset = 1, uint32 = 0xFF1F7FFF}
        }
      });
```
I don't want to create a gradient per key (with the key specific coordinates), I want to use the same gradient for all.  Is the proper way to do this using the matrix operation on the gradient before drawing each key?

```C
BL_API_C BLResult BL_CDECL blGradientApplyMatrixOp(BLGradientCore* self, uint32_t opType, const void* opData) BL_NOEXCEPT_C;
```
I'm assuming if I make my gradient a unit of 1, then just scale and translate appropriately, that's the right way to do it?  Or is there another method I'm missing?

**Comment by Wiladams** [comment]
As an issue, I think there is a difference between the pixels covered from fillRoundedRect and strokeRoundedRect.  I'll have to do some experimentation to quantify exactly what the difference is, but you can see it a bit in this blown up image.

**Comment by Wiladams** [comment]
values are actually:
```lua
        values = {obj.unit/2, 0, obj.unit/2, obj.unit};
```

**Comment by Wiladams** [comment]
Now that I've read the contributing guidelines, I'll move this over to the gitter discussion instead of here.

**Comment by kobalicek** [comment]
I will reply on gitter, thanks for patience :)
