### ISSUE TITLE
Conical gradient's angle doesn't affect rendering

### ISSUE THREAD

**Issue by LuizZak** [blend2d/blend2d#31]
I'm assuming the `angle` property of `BLConicalGradientValues` is meant to affect the angle of the resulting conical gradient, but it seems like it does nothing.

I've checked and it seems like this value is read here: https://github.com/blend2d/blend2d/blob/master/src/blend2d/blpipedefs.cpp#L506

but it doesn't seem to use that variable at all.

**Comment by kobalicek** [comment]
Yeah this is true, angle should additionally transform the input matrix, I will check this out when I finish my current work

**Comment by fjpietr** [comment]
I did some empirical investigation on this...

![image](https://user-images.githubusercontent.com/59561905/71990443-aae3d400-3233-11ea-9a1f-6410d7c0d1e9.png)

It seems to me that the translation part of the final transform is being applied twice... this seems to fix both gradient angle and wrong position (pipedefs.cpp):

[blPipeFetchDataInitConicalGradient.cpp.txt](https://github.com/blend2d/blend2d/files/4036006/blPipeFetchDataInitConicalGradient.cpp.txt)

now everything aligns up correctly, even with additional rotations and scaling transforms in the stack:

![image](https://user-images.githubusercontent.com/59561905/71992193-52153b00-3235-11ea-828d-43297875e82f.png)

**Comment by fjpietr** [comment]
Confirmed working!

**Comment by kobalicek** [comment]
Merged thanks!
