### ISSUE TITLE
Odd behavior when subtracting box inside another box with BLRegion

### ISSUE THREAD

**Issue by LuizZak** [blend2d/blend2d#37]
When applying the following operations to an empty `BLRegion`:

```swift
region.combine(box: BLBoxI(x0: 0, y0: 0, x1: 100, y1: 100), operation: BL_BOOLEAN_OP_OR)
region.combine(box: BLBoxI(x0: 25, y0: 25, x1: 75, y1: 75), operation: BL_BOOLEAN_OP_SUB)
```

I expected the resulting region to contain four rectangles, outlining an empty square of size 50x50 within, but the result only contains three rectangles with a missing right rectangle:

```
impl->view:

[
    BLBoxI(x0: 0, y0: 0, x1: 100, y1: 25),
    BLBoxI(x0: 0, y0: 25, x1: 25, y1: 75),
    BLBoxI(x0: 0, y0: 75, x1: 100, y1: 100)
]
```

Illustrated diagram:

![Untitled Diagram](https://user-images.githubusercontent.com/6502879/58426901-4e50f180-8074-11e9-92b4-129f32d0f26a.png)

**Comment by cs-luiz-silva** [comment]
I pulled the latest changes and it seems to be corrected! Thanks for the quick turnaround on this one.

**Comment by LuizZak** [comment]
Oops commented on my work account. Anyways, I'll be closing this as resolved.

**Comment by kobalicek** [comment]
Thanks for the bug report!
