### ISSUE TITLE
crash while stroking rect with clip translate combo

### ISSUE THREAD

**Issue by Wiladams** [blend2d/blend2d#38]
This test case fairly isolates a crash I have found.  Basically, the combination of doing a clip, and then a translate, and then a strokeRect which would fall outside the bounds of the underlying image, will crash.  I suspect it's outside the bounds of checking on the image, and writes into random memory or something.

The code here is lua, but the C equivalent should be the same.

```lua
package.path = "../?.lua;"..package.path;

local ffi = require("ffi")
local C = ffi.C 

local blapi = require("blend2d/blend2d_ffi")

local BLContext = ffi.typeof("BLContextCore")
local BLImage = ffi.typeof("BLImageCore")
local BLRectI = ffi.typeof("BLRectI")
local BLRect = ffi.typeof("BLRect")


local function _applyMatrixOpV(ctx, opType, ...)
    local opData = ffi.new("double[?]",select('#',...), {...});
    --print("_applyMatrixOpV: ", opData[0], opData[1])
    local bResult = ctx.impl.virt.matrixOp(ctx.impl, opType, opData);
    if bResult == C.BL_SUCCESS then
        return self;
    end

    return false, bResult
end

local function translate (ctx, x, y)
    return _applyMatrixOpV(ctx, C.BL_MATRIX2D_OP_TRANSLATE, x, y);
end

local function main()
    local x = 390
    local y = 10
    local width = 100
    local height = 100

    local img = BLImage()
    blapi.blImageInitAs(img, 400, 400, C.BL_FORMAT_PRGB32)
    local ctx = BLContext()
    blapi.blContextInitAs(ctx, img, nil)

    local rect = BLRectI({x,y,width,height})
    blapi.blContextClipToRectI(ctx, rect) ;
    
    local err = translate(ctx, x, y)

    -- stroke
    -- THIS WILL CRASH
    local bResult = blapi.blContextStrokeRectD(ctx, rect) ;
end

main()
```

**Comment by Wiladams** [comment]
Narrowing it down further, it definitely seems to be something right around the border, when the stroke rectangle is crossing over the limit of the bitmap.  Windows 10 (64-bit OS), blend2d built as 32-bit.
```lua
local function main()
    local x = 390
    local y = 10
    local width = 100
    local height = 100

    -- setup context
    local img = BLImage()
    blapi.blImageInitAs(img, 400, 400, C.BL_FORMAT_PRGB32)
    local ctx = BLContext()
    blapi.blContextInitAs(ctx, img, nil)

    local recti = BLRectI({x,y,width,height})
    print("blContextClipToRectI: ", blapi.blContextClipToRectI(ctx, recti)) ;


    translate(ctx, x, y)

    --local srecti = BLRectI(0,0,width,height)
    local srecti = ffi.new("BLRectI")
    srecti.x = 0;
    srecti.y = 0;

    srecti.h = 10;
    -- will NOT crash
    --srecti.w = 13;
    -- WILL crash
    srecti.w = 14;

    blapi.blContextStrokeRectI(ctx, srecti)
end
```

**Comment by Wiladams** [comment]
still working it.  I can get it to NOT crash in another circumstance by rearranging code, so I'm back to thinking it might be a LuaJIT interaction.

**Comment by Wiladams** [comment]
Rearranged code, got as raw as possible
```lua
    -- will NOT crash
    --srecti.w = 14;

    -- WILL crash
    srecti.w = 15;
```
Can still reliably reproduce a crash.  I guess next thing is to use C instead of Lua to completely eliminate that as a possibility, and crack out the debugger to figure out where it's actually crashing.

**Comment by kobalicek** [comment]
Should be fixed by blend2d/blend2d@b27e2b2

**Comment by Wiladams** [comment]
fixes the crash, but introduces new challenges.  Now, when I setup a clip, then draw beyond, all subsequent drawing after that will not occur, until a clearAll().

**Comment by Wiladams** [comment]
as a proof point that this issue has been fixed, several examples of complex clipping that previous showed challenges

<img width="963" alt="Clipping" src="https://user-images.githubusercontent.com/457634/58751011-ba32c000-84a1-11e9-9520-763bb71f14f0.PNG">
