### ISSUE TITLE
index_sequence should be renamed to integer_sequence

### ISSUE THREAD

**Issue by prideout** [blend2d/blend2d#43]
blend2d fails to build on platforms that properly support C++ 14, which provides a class called `std::integer_sequence` (with 2 template arguments) rather than a class called `std::index_sequence` (with 1 template argument).

I recommend using TravisCI to build blend2d with a small handful of platforms, it is free and surprisingly easy to set up.

**Comment by kobalicek** [comment]
There is already travis-ci setup:
  https://travis-ci.org/blend2d/blend2d

However, it seems it doesn't catch this one. I initially developed Blend2D in C++17 so this must be something that I broke during refactoring to use C++11 and C-API. I will take a look.

BTW: I'm not sure how to use CMake to use C++17 when I specify that it just required C++11. It would be nice to have the CI setup to use all possible standards.

**Comment by kobalicek** [comment]
BTW I have just tried to force C++14 and C++17 and I see no problem in compilation, can you elaborate?

**Comment by prideout** [comment]
Ah nice!  I didn't see a Travis badge in the README so assumed that one didn't exist.

Here's the build log for the error I'm seeing:
https://travis-ci.org/prideout/clumpy/jobs/547362981

**Comment by kobalicek** [comment]
Isn't this caused by using C++14 standard with an older libstdc++ that doesn't support it? This would definitely be possible to avoid as Blend2D compiles just fine in C++11 mode, but I would need to know how to detect that libstdc++ doesn't support C++14.

**Comment by kobalicek** [comment]
I have committed a potential fix:
  https://github.com/blend2d/blend2d/commit/d68d210912fc8adc491ad0b07e50216c1a37f856

**Comment by prideout** [comment]
Thanks, this fixes issue the on my end.  Also I found `index_­sequence` in the ISO spec, so apologies for the bogus bug title.
