### ISSUE TITLE
Confusion around fitFlags on BLPath::fitTo

### ISSUE THREAD

**Issue by alexlitty** [blend2d/blend2d#44]
Is there future intent for `BLPath::fitTo`'s `fitFlags` parameter? If not, would its removal be considered?

I wasn't able to find any uin32_t flags in the docs, eventually had to dig up the source, and found the parameter isn't honored right now: https://github.com/blend2d/blend2d/blob/master/src/blend2d/blpath.cpp#L1912

p.s. Super wonderful project :) Very impressed with it overall.

**Comment by kobalicek** [comment]
True, this is not implemented, at the moment what you get is stretch behavior. I think we have opened this topic on gitter once but haven't reached any agreement on how different stretch flags should be defined.

I think the closest definition would be this:
  https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit

I will open this question again on gitter and let's see whether we can reach an agreement.

**Comment by kobalicek** [comment]
Or maybe this could be even better:
  - https://www.w3.org/TR/SVG11/coords.html#PreserveAspectRatioAttribute

**Comment by kobalicek** [comment]
Closing this in favor of https://github.com/blend2d/blend2d/issues/92
