### ISSUE TITLE
ctx->fillStyleType always returns 1 (BL_STYLE_TYPE_SOLID)

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#47]
Please, see  sample  "bl-getting-started-2.cpp".

After setting a a fill-style with a gradient
  ctx.setFillStyle(linear);
if a try to check the "current-fill style"
  ctx.fillStyleType()
this method return 1 (i.e. BL_STYLE_TYPE_SOLID), instead of 3 (BL_STYLE_TYPE_GRADIENT).

**Comment by kobalicek** [comment]
Thanks! I have completely overlooked this, I will fix this soon.

**Comment by abu-irrational** [comment]
just a note:
same bad behaviour using a BLPattern instead of a BLGradient.

**Comment by kobalicek** [comment]
Thanks! Should be fixed by now.
