### ISSUE TITLE
There is a serious bug that blitImage behaves incorrectly。

### ISSUE THREAD

**Issue by ghphg** [blend2d/blend2d#49]
BLPointI pt(10, 10);
ctx.blitImage(pt, image);
ctx.translate(200, 30);
ctx.blitImage(pt, image);
![blitImage](https://user-images.githubusercontent.com/4328485/65445060-f8def280-de63-11e9-998a-bd55387707fd.png)

**Comment by kobalicek** [comment]
Should be fixed by https://github.com/blend2d/blend2d/commit/766f2f33c81f92067552e5cb18edf5d69dbb45fb
