### ISSUE TITLE
Wrong saved BMPs

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#51]
Please see the attached BMP within the zip file.
They have been generated with the same simple app (see below), a variant of "bl-getting-started-1.cpp"
The bmp generated from a BLImage sized 330x330 (XRGB32) is wrong,
The bmp generated from a BLImage sized 332x332 (XRGB32) iscorrect,

I guess it's because the image-width (330) is not divisible by 4.
Note that a BLImage 300x300 (PRGB32) is saved correctly.
===========================================================
#include <blend2d.h>

int main(int argc, char* argv[]) {
  //    BLImage img(332, 332, BL_FORMAT_XRGB32);  // OK
  //  BLImage img(330, 330, BL_FORMAT_PRGB32);  // OK

  BLImage img(330, 330, BL_FORMAT_XRGB32);  // wrong saved image
 
  BLContext ctx(img);
  // Clear the image.
  ctx.setCompOp(BL_COMP_OP_SRC_COPY);
  ctx.fillAll();

  ctx.setFillStyle(BLRgba32(0xFFFF0000));  //red
  ctx.fillCircle(100,100,50);

  // Detach the rendering context from `img`.
  ctx.end();

  // Let's use some built-in codecs provided by Blend2D.
  BLImageCodec codec;
  codec.findByName("BMP");
  img.writeToFile("bl-getting-started-1x.bmp", codec);

  return 0;
}
==============================

[XRGB-test.zip](https://github.com/blend2d/blend2d/files/3709515/XRGB-test.zip)

**Comment by kobalicek** [comment]
Thanks! Let me know whether it fixes the issue.

**Comment by abu-irrational** [comment]
OK. Fixed..
