### ISSUE TITLE
Error loading PNG with transparent pixels

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#52]
Here is the original PNG file  (background is completeley transparent)
![RGBtransp](https://user-images.githubusercontent.com/13416847/66611684-9ace4100-ebbf-11e9-8ab4-2706828a0679.png).
I simply loaded this PNG using
   img.readFromFile("RGBtransp.png")
.. see the full code below.
and here is how it appears, and how it is saved (as a BMP), here post-converted to PNG just for attaching it in this post)
![resultingRGB](https://user-images.githubusercontent.com/13416847/66611979-7a52b680-ebc0-11e9-8dba-0dc3079fa20d.png)

I guess the bug is within readFromFile() method and not in the writeToFile() method, because (using another app) I can see the (wrong) image just loaded.
I used the following code.

```
int main(int argc, char* argv[]) {
  BLImage img;
  BLResult err = img.readFromFile("RGBtransp.png");
  if (err) {
    printf("Failed to load a texture (err=%u)\n", err);
    return 1;
  }
  BLContext ctx(img);
  ctx.end();

  BLImageCodec codec;
  codec.findByName("BMP");
  img.writeToFile("resultingRGBtransp.bmp", codec);

  return 0;
}
```

**Comment by kobalicek** [comment]
Thanks, I would ask for the file.

The problem with the saved BMP could be that the viewer could consider it as unpremultiplied, but Blend2D saves it as premultiplied. If the image renders correctly as a texture then I would say it's read properly, but we will see.

**Comment by abu-irrational** [comment]
Here is the original PNG.
[RGBtransp.zip](https://github.com/blend2d/blend2d/files/3716296/RGBtransp.zip).
I can confirm that with *my* viewer it appears wrong (and this could be a problem of my viewer with premultiplied aplha... ). Anyway, when I save the loaded BLImage, the error is evident.

**Comment by kobalicek** [comment]
I can confirm that Blend2D is correct in this case. Here is the same image loaded by GIMP blended into a black layer.

![image](https://user-images.githubusercontent.com/6491301/66700109-6193ef00-eced-11e9-8c81-e9b3b7b2f8af.png)
