### ISSUE TITLE
Incompatibility with Unreal4 requirements

### ISSUE THREAD

**Issue by gribuser** [blend2d/blend2d#53]
Impossible to build blend2d (or use the prebuilt dll) with Unreal Engine. There are "warnings" 4582 and 4583, preventing build (for whatever reason, multiplatform and all that). Disabling warnings does not help too, other errors arise.
I'm not sure it's a true bug, just C++ code imperfection. Yet here you go:

> 2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blpath.h(225): error C4582: 'BLStrokeOptionsCore::dashArray': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blpath.h(225): error C4583: 'BLStrokeOptionsCore::dashArray': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4582: 'BLFontFaceImpl::data': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4582: 'BLFontFaceImpl::loader': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4582: 'BLFontFaceImpl::fullName': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4582: 'BLFontFaceImpl::familyName': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4582: 'BLFontFaceImpl::subfamilyName': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4582: 'BLFontFaceImpl::postScriptName': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4583: 'BLFontFaceImpl::data': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4583: 'BLFontFaceImpl::loader': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4583: 'BLFontFaceImpl::fullName': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4583: 'BLFontFaceImpl::familyName': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4583: 'BLFontFaceImpl::subfamilyName': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(411): error C4583: 'BLFontFaceImpl::postScriptName': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(627): error C4582: 'BLFontImpl::face': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(627): error C4582: 'BLFontImpl::features': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(627): error C4582: 'BLFontImpl::variations': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(627): error C4583: 'BLFontImpl::face': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(627): error C4583: 'BLFontImpl::features': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blfont.h(627): error C4583: 'BLFontImpl::variations': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blimage.h(606): error C4582: 'BLImageDecoderImpl::codec': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blimage.h(606): error C4583: 'BLImageDecoderImpl::codec': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blimage.h(733): error C4582: 'BLImageEncoderImpl::codec': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\blend2d\./blimage.h(733): error C4583: 'BLImageEncoderImpl::codec': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\./blend2d/blcontext.h(367): error C4582: 'BLContextState::strokeOptions': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\./blend2d/blcontext.h(367): error C4583: 'BLContextState::strokeOptions': destructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\./blend2d/blpattern.h(52): error C4582: 'BLPatternImpl::image': constructor is not implicitly called
2>D:\Work\Unreal\TerrainGeneration01\Source\blend2d\src\./blend2d/blpattern.h(52): error C4583: 'BLPatternImpl::image': destructor is not implicitly called

**Comment by kobalicek** [comment]
Is anywhere described what are the "Unreal 4" requirements? Blend2D is at the moment compiled with `-W4` on Windows, which enables warnings level 4 and I haven't seen the warnings that you posted. I think it would be the best to conditionally disable these warnings if they are the problem, however, what Blend2D does is a valid use of C++11 features and all of these warnings are related to providing compatibility with C.

I definitely need more information regarding this issue. VS version, etc.

**Comment by kobalicek** [comment]
This should be fixed with commit https://github.com/blend2d/blend2d/commit/8d05b27f4445d9d53335f85fb97f53fa5fa77fce in which Blend2D disables these warnings during the inclusion of `<blend2d.h>` and during the build. Please reopen if the fix is not enough.
