### ISSUE TITLE
Color issues in latest beta release

### ISSUE THREAD

**Issue by LuizZak** [blend2d/blend2d#54]
The latest release on master seems to have broken something related to colors, as is shown on this sample:

```swift
let img = BLImage(width: 480, height: 480, format: .prgb32)

let ctx = BLContext(image: img)!

// Fill a white background
ctx.compOp = .sourceCopy
ctx.setFillStyleRgba32(0xFFFFFFFF)
ctx.fillAll()

// Fill a centered blue box
ctx.compOp = .sourceOver
ctx.setFillStyleRgba32(0xFF0000FF)
ctx.fillRect(BLRect(x: 100, y: 100, w: 280, h: 280))

ctx.end()
```

I expect a blue rectangle to be produced, but instead I get a black box:

![snappy](https://user-images.githubusercontent.com/6502879/71524111-c56c9380-28aa-11ea-8488-2d4bda64ef1a.png)

The standard tiger sample also shows wrong colors now:

![tiger_actual](https://user-images.githubusercontent.com/6502879/71524089-b5ed4a80-28aa-11ea-9f3e-c28a0642b048.png)

**Comment by kobalicek** [comment]
BTW did you update your bindings? Just asking as the layout of Impls has been changed. I will take a look, but my tests are pretty much okay.

**Comment by LuizZak** [comment]
Even invoking the raw C api seems to be producing different results, e.g. filling an empty context produces a transparent background vs. a black one like it used to. I'll check if it's something to do with the files that where moved and such.

**Comment by kobalicek** [comment]
Ok, I think this could be caused by PipeGen. Since I have a machine with AVX2 instructions maybe there is something wrong in a code-path that is used when AVX2 is not present.

**Comment by kobalicek** [comment]
Let me know if this commit fixes the issue:
 
 https://github.com/blend2d/blend2d/commit/bddae39a210aa48c839901584eec647c8ae1b967

**Comment by LuizZak** [comment]
Looks good now!
