### ISSUE TITLE
Bad gradients with source over operator

### ISSUE THREAD

**Issue by fjpietr** [blend2d/blend2d#55]
Hi, apparently there's a problem when filling paths with linear or radial gradients and source over operator on non transparent backgrounds (other composition modes are ok, and if I recall correctly beta9 was working good). "Bands" appear where not fully opaque pixels are drawn. I'm attaching screenshots, debug info, isolated test case program code and output.

![screenshots](https://user-images.githubusercontent.com/59561905/71826363-067c5900-309e-11ea-9553-a3bd6afe3d9d.png)

[blend2d debug output.txt](https://github.com/blend2d/blend2d/files/4026573/blend2d.debug.output.txt)

[test_case.cpp.txt](https://github.com/blend2d/blend2d/files/4026577/test_case.cpp.txt)

![test_case_output](https://user-images.githubusercontent.com/59561905/71826456-42afb980-309e-11ea-9107-e306713f4730.png)

**Comment by kobalicek** [comment]
Thanks a lot! You were right as I have introduced this issue in my latest work.

Let me know whether the commit above fixes the issue.

**Comment by fjpietr** [comment]
Tested, works!
