### ISSUE TITLE
Seams with repeating pattern fill style

### ISSUE THREAD

**Issue by fjpietr** [blend2d/blend2d#56]
Hi again, there's a problem with filtering across pattern edges when
applying a matrix to a style that contains a rotation. Depending on the
rotation angle there are zero, two or four hard unfiltered seams in the
output. Here are some screenshots taken from my project:

![0_90](https://user-images.githubusercontent.com/59561905/71893927-2dde2f00-314d-11ea-9986-75c9cac3e4ce.png)

![90_180](https://user-images.githubusercontent.com/59561905/71893961-44848600-314d-11ea-9d6c-44b8b055b86a.png)

![180_270](https://user-images.githubusercontent.com/59561905/71893973-4c442a80-314d-11ea-8abc-f22c27ac92ca.png)

![270_360](https://user-images.githubusercontent.com/59561905/71893990-582fec80-314d-11ea-85af-c970dd949e41.png)

the test case:

[pattern_seams.cpp.txt](https://github.com/blend2d/blend2d/files/4030516/pattern_seams.cpp.txt)

the checker image to use with the test case:

![checker](https://user-images.githubusercontent.com/59561905/71894352-4d298c00-314e-11ea-8bf7-c0c244e0cd82.png)

However I'm not able to fully replicate the behaviour of my app in the test case,
since it seems to show always either no seams (when angle is between 0
and 90°) or four seams, across both u and v texture axis.

**Comment by kobalicek** [comment]
Let me know whether that fixes the issue, I did only basic testing so far

**Comment by fjpietr** [comment]
Excellent! Patterns are now smooth as silk, Sir. Thank you!

**Comment by kobalicek** [comment]
Thanks for the report, this was really an interesting one. And I consider the fix as not so great, thinking about a better one that would not introduce another variable.

**Comment by fjpietr** [comment]
Actually the seam was somewhat difficult to spot at 1x magnification with most patterns, it became evident only after implementing pixel preview when zooming. Testing your commit now.

**Comment by kobalicek** [comment]
Yeah I missed it too while implementing this feature - it was only wrong when the texture increment was negative in repeat-only mode - both pad and reflect were okay.

**Comment by fjpietr** [comment]
Eheh, that sneaky corner cases. Well, goodbye seams and chkX/chkY, I confirm that your latest patch works perfectly.
