### ISSUE TITLE
ld-elf.so.1: /usr/local/lib/libblend2d.so: Undefined symbol "_ZN6asmjit12ErrorHandlerD2Ev"

### ISSUE THREAD

**Issue by yurivict** [blend2d/blend2d#57]
It looks like you forgot -lasmjit when you linked the library.

asmjit is installed from the FreeBSD package (that I just created).
It should be able to link to the library from there properly.

Yuri

**Comment by kobalicek** [comment]
I would strongly recommend to not link asmjit dynamically in this case - asmjit doesn't guarantee ABI stability so it's like asking for trouble. This is the main reason asmjit is bundled in Blend2D source packages and embedded in Blend2D.

Another reason is that these two projects are developed very closely, so when there is a new thing added to asmjit it can be immediately used by Blend2D.

**Comment by kobalicek** [comment]
In retrospective, I will add option to link asmjit dynamically, but it won't be default.

**Comment by kobalicek** [comment]
This should be fixed in master and 0.11.1 version. There is a new CMake option `BLEND2D_EXTERNAL_ASMJIT`, which would instrument cmake to use non-bundled (possibly system) AsmJit.

I still don't recommend this, but it's now possible.
