### ISSUE TITLE
AVX/AVX2 detection vs target runtime

### ISSUE THREAD

**Issue by iryont** [blend2d/blend2d#58]
Hello

I have some doubts regarding AVX/AVX2. Blend2D checks if the compiler supports avx/avx2 and if so, it sets its flags:

```
blend2d_detect_cflags(BLEND2D_CFLAGS_AVX "-arch:AVX")
blend2d_detect_cflags(BLEND2D_CFLAGS_AVX2 "-arch:AVX2")
```

Then we can see in the runtime_p.h that if certain flags regarding AVX/AVX2 were enabled then everything is const valued and evaluates to true without checking actual runtime:

```cpp
#ifdef BL_TARGET_OPT_AVX
constexpr bool blRuntimeHasAVX(BLRuntimeContext* rt) noexcept { return true; }
#else
inline bool blRuntimeHasAVX(BLRuntimeContext* rt) noexcept { return (rt->systemInfo.cpuFeatures & BL_RUNTIME_CPU_FEATURE_X86_AVX) != 0; }
#endif

#ifdef BL_TARGET_OPT_AVX2
constexpr bool blRuntimeHasAVX2(BLRuntimeContext* rt) noexcept { return true; }
#else
inline bool blRuntimeHasAVX2(BLRuntimeContext* rt) noexcept { return (rt->systemInfo.cpuFeatures & BL_RUNTIME_CPU_FEATURE_X86_AVX2) != 0; }
#endif
```

Basically what I want to make sure of is that runtime detects CPU features on the target computer despite my compiler supporting AVX/AVX2. Just because my compiler supports it doesn't mean the end user will have a CPU supporting AVX/AVX2.

Then again I can see this part within api-build_p.h:

```
#if defined(__AVX2__)
  #define BL_TARGET_OPT_AVX2
#endif
#if defined(BL_TARGET_OPT_AVX2) || defined(__AVX__)
  #define BL_TARGET_OPT_AVX
#endif
```

Since I do use MSVC 19 I can assume \_\_AVX2\_\_ won't be defined unless I specify AVX2 extension within code generation section.

By looking at gradient.cpp I can see that the runtime is checked:

```cpp
  #ifdef BL_BUILD_OPT_SSE2
  if (blRuntimeHasSSE2(rt)) {
    blGradientOps.interpolate32 = blGradientInterpolate32_SSE2;
  }
  #endif

  #ifdef BL_BUILD_OPT_AVX2
  if (blRuntimeHasAVX2(rt)) {
    blGradientOps.interpolate32 = blGradientInterpolate32_AVX2;
  }
  #endif
```

So I can only assume those flags are only to check whether compiler supports AVX/AVX2, but it is always checked at the runtime nonetheless, and if so, used, if not - not.

**Comment by kobalicek** [comment]
I think you misunderstood how these flags work, there are two kind of flags: 
  - `BL_BUILD_OPT_XXX` - These macros define supported CPU features above baseline by the build.
  - `BL_TARGET_OPT_XXX`  - These macros define actual CPU features for the compilation unit.

Thus, defining BL_BUILD_OPT_AVX2 means that Blend2D would support some AVX2 optimized functions, but won't rely on AVX2 presence, whereas BL_TARGET_OPT_AVX2 means that at the moment the compilation unit requires AVX2, which is used by all files with _avx2.cpp suffix.

Blend2D baseline optimization level is SSE2, anything above id dispatched at runtime.

**Comment by iryont** [comment]
I thought I did misunderstand it, thankfully. I'm glad to hear that.

Appreciated the answer. SSE2 as baseline is fine because I will be compiling for x64 anyway, so kind of implicit.

One more question though, I did see on the website the multithreaded rendering is still being worked on. Is it within the repository or not published as of yet? I'm asking because I've seen BLContextCreateInfo::threadCount and I wonder whether it is useful right now or a placeholder.

**Comment by kobalicek** [comment]
MT rendering is not ready yet and you should see `BLContextCreateInfo` as something that would make more sense in the future. At the moment `threadCount` makes no difference. I'm usually developing such features privately and once I'm confident that the stability is okay I push them to master for community testing and feedback.

**Comment by iryont** [comment]
Understood. I was going through the code seeing some static class which called blRuntimeInit which then acquired amount of threads based on the CPU and fed it into BLRuntimeContext, but I couldn't find any use of it.

That being the case, I'm looking forward to it. I will be soon trying Blend2D for a 2D game with a lot of drawcalls and sprites. I have already backends of OpenGL, DirectX and SDL2 (which has its own software renderer, but it isn't optimized very well). I kind of hope Blend2D will turn out better than SDL2 software renderer.
