### ISSUE TITLE
Clang in MSVC 2019

### ISSUE THREAD

**Issue by iryont** [blend2d/blend2d#59]
Hello again

Blend2D suggest to use Clang, so I did generate the build project files for MSVC 2019 with clang installed using the following command:

```
cmake -T ClangCL .. -DBLEND2D_STATIC=True
```

It did generate project with LLVM (clang-cl) as Platform Toolset, but there are some warnings:

```
2>clang-cl : warning : unknown argument ignored in clang-cl: '-fno-exceptions' [-Wunknown-argument]
2>clang-cl : warning : unknown argument ignored in clang-cl: '-fno-rtti' [-Wunknown-argument]
2>clang-cl : warning : unknown argument ignored in clang-cl: '-fno-math-errno' [-Wunknown-argument]
```

Which I suppose might be crucial for those optimizations mentioned on the website regarding choosing compiler.

The project does compile fine though.

**Comment by kobalicek** [comment]
Do you know how to pass these to clang-cl or it's a complete nonsense? With CMake it's really hard to avoid CMake defaults in this case, which turn exceptions on. This is definitely an issue that I would like to fix for both MSVC and Clang.

**Comment by martin31821** [comment]
You can pass `-XClang $arbitraryOption` to `clang-cl` as well as `oclang` (for mac os) to pass the default linux clang options.

**Comment by iryont** [comment]
martin31821 is right:

https://clang.llvm.org/docs/UsersManual.html#clang-cl

```
  -Xclang <arg>           Pass <arg> to the clang compiler
```

That should be trivial fix within cmake file.

**Comment by iryont** [comment]
Perhaps it might not be possible after all. Xclang does not appear to be working as I expected it to work. Some insight:

https://reviews.llvm.org/D53457

However, we are indeed lucky, the funny fact is that /clang: was actually implemented within clang-cl. So the following does the trick:

```
list(APPEND BLEND2D_PRIVATE_CFLAGS /clang:-fno-exceptions /clang:-fno-rtti /clang:-fno-math-errno)
```

Well, almost, since we are getting those warnings:

```
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
2>clang-cl : warning : argument unused during compilation: '-fno-exceptions' [-Wunused-command-line-argument]
```

The rest went away though.

**Comment by iryont** [comment]
Those flags are used during compilation:

```
/c /I"C:\X64-LIBS\BLEND2D\3RDPARTY\ASMJIT\SRC" /nologo /W4 /WX- /diagnostics:column /O2 /Ob2 /Oi /D WIN32 /D _WINDOWS /D NDEBUG /D BL_STATIC /D BL_BUILD_OPT_AVX2 /D ASMJIT_STATIC /D ASMJIT_NO_STDCXX /D "CMAKE_INTDIR=\"Release\"" /D _MBCS /EHsc /MD /GS- /fp:precise /GR- /Fo"BLEND2D.DIR\RELEASE\\" /Gd /TP -m64   -Zc:strictStrings -Zc:threadSafeInit- -volatile:iso /clang:-fno-exceptions /clang:-fno-rtti /clang:-fno-math-errno C:\X64-LIBS\BLEND2D\SRC\BLEND2D\API-NOCXX.CPP
```

Perhaps it ignores -fno-exceptions because of /EHsc which states:

*If you use /EHs or /EHsc, then your catch(...) clause does not catch asynchronous structured exceptions. Access violations and managed System.Exception exceptions are not caught, and objects in scope when an asynchronous exception is generated are not destroyed even if the asynchronous exception is handled.*

**Comment by kobalicek** [comment]
I tried to fix all the warnings in https://github.com/blend2d/blend2d/commit/7f88f7be297144c8b068f1a24197a6eb2806907c, however, the `-fno-exceptions` is not possible this way, so I have to find another way to set it.

**Comment by iryont** [comment]
Seems like it was taken care of. I suppose we might as well just close this issue? After all, it's pretty much resolved, unless of course you want to keep it open for the no-exceptions.

**Comment by kobalicek** [comment]
Yeah closing, I don't think I can fix the exception options today and it's not critical anyway :)
