### ISSUE TITLE
clipToRect issue

### ISSUE THREAD

**Issue by iryont** [blend2d/blend2d#61]
I'm not sure if I'm doing it right, but clipToRect appears to be broken or at least not working as expected. I have a rendering class which uses it like this:

```cpp
void Renderer::setClipRect(const Rect& clipRect)
{
    BLRectI rect;
    if(m_clipRect.isValid()) {
        rect.x = m_clipRect.x();
        rect.y = m_clipRect.y();
        rect.w = m_clipRect.width();
        rect.h = m_clipRect.height();
    } else {
        rect.x = 0;
        rect.y = 0;
        rect.w = m_context->targetWidth();
        rect.h = m_context->targetHeight();
    }

    m_context->clipToRect(rect);
}
```

However, it seems to accumulate clipToRect each time it is called and therefore actual clipping rect is invalid.

In order for the clip to work properly (like in any other rendering backend such as OpenGL or DirectX) I have to call **restoreClipping** each time before setting the actual clipping rectangle:

```c++
void Renderer::setClipRect(const Rect& clipRect)
{
    m_context->restoreClipping();

    BLRectI rect;
    if(m_clipRect.isValid()) {
        rect.x = m_clipRect.x();
        rect.y = m_clipRect.y();
        rect.w = m_clipRect.width();
        rect.h = m_clipRect.height();
    } else {
        rect.x = 0;
        rect.y = 0;
        rect.w = m_context->targetWidth();
        rect.h = m_context->targetHeight();
    }

    m_context->clipToRect(rect);
}
```

Is this intended behavior?

**Comment by kobalicek** [comment]
This is actually the intended behavior at the moment.

To explain this a bit - there should be no way to escape a clip region after it has been established. For example, if you save it in `save()` call, there should be no way to going back unless you call `restore()` - and this can be combined with ContextCookie, preventing to restore the state unless the cookie is given, effectively preventing rendering into regions outside the clipBox.

Of course I'm open to new ideas or enhancements in this area.

**Comment by iryont** [comment]
In such case there is no need to change it. Inability to escape clipping region should be just explicitly mentioned and everyone can cover that case in their own code.

I'm fine with the current behavior. I do not believe there is any need to change it, so I will take the liberty of closing this issue.
