### ISSUE TITLE
Delete Shape

### ISSUE THREAD

**Issue by CNchence** [blend2d/blend2d#63]
Can blend2d save all drawn graphics and delete a shape after drawing?

**Comment by kobalicek** [comment]
I'm afraid I don't understand the question, can you elaborate?

**Comment by CNchence** [comment]
I want to use blend2D to implement a simple 2D UI drawing. I need to draw straight lines, rectangles, circles, and arcs. By following the code example, I was able to save the shape to be drawn into a BLPath, and then use BLContext to draw the BLPath. What I want to ask is, how to delete a shape that has been added from BLPath?

**Comment by kobalicek** [comment]
Ok, so you are missing a BLPath API that would allow you to delete vertices from the path, correct?

**Comment by kobalicek** [comment]
Checkout this branch and let me know whether this is the missing functionality you are looking for:

https://github.com/blend2d/blend2d/tree/path_range

**Comment by CNchence** [comment]
Thank you for your reply, this is the api I need, but I found that when deleting more than two shapes in a BLPath, the code incorrectly draws an extra straight line, and the extra straight lines are related to the two deleted shapes . For example, at the beginning I will have four straight lines in a BLPath, I delete two of them, and then draw the BLPath, and three straight lines will appear in the result.

**Comment by kobalicek** [comment]
Do you have a sample code that would demonstrate the behavior? The function accepts a `[start, end)` range, so maybe you are keeping one vertex there. You can use `blDebugPath()` (`#include <blend2d-debug>`)to dump the content of a path in a possible repro of the issue.

**Comment by kobalicek** [comment]
I would close this issue at the end of the week if there is no sample that would repro the issue.

**Comment by kobalicek** [comment]
Deleting path range has been merged into master branch, please reopen if it doesn't work as expected.
