### ISSUE TITLE
SIGSEGV when filling BLPath

### ISSUE THREAD

**Issue by fjpietr** [blend2d/blend2d#64]
Hi, it seems that under certain circumstances filling a path made of lines and bezier cubic segments causes a segmentation fault in Blend2D. Unluckily the bug (bugs probably, two distinct code locations seem to be involved) it's not easy to reproduce, I'll try to document the best I can at the moment.

**1st scenario**: in the test case a setting a clipping rectangle causes a segmentation fault; when there's no clipping rectangle set the output is correct.

Test case:
[testcase.cpp.txt](https://github.com/blend2d/blend2d/files/4211532/testcase.cpp.txt)

(The odd values come from dumping the path data from my editor, see below)

Unclipped result (correct):
![result](https://user-images.githubusercontent.com/59561905/74619304-5b979a00-5135-11ea-930f-ab364098875e.png)

Backtrace:
[test_case_gdb_traceback.txt](https://github.com/blend2d/blend2d/files/4211538/test_case_gdb_traceback.txt)

**2nd scenario**: In my project, with the same path of the test case ad no clipping rectangle set, the error originates somewhere else. I can't do much more than attaching gdb traceback from the core dump:

[my_project_gdb_backtrace.txt](https://github.com/blend2d/blend2d/files/4211539/my_project_gdb_backtrace.txt)

Bomb here:
```
in BLEdgeBuilder<int>::_linkEdge (this=0x55dcb8eaf630, edge=0x55dcb8eb0518, y0=-2147483648)
blend2d/src/blend2d/raster/../raster/edgebuilder_p.h:2263
2263	    edge->next = _bands[bandId];
```

This seems related to curve flattening; passing the path already flattened by other means doesn't cause segmentation faults.

Another observation: moving the path from its location, even shifting it one pixel along x or y axis, prevents the segmentation fault.

**Comment by fjpietr** [comment]
In the **2nd scenario** (`edgebuilder_p.h crash when edge->next = _bands[bandId]`) the segfault is triggered by having the left and right edges of the path being exactly aligned with the image left a right borders. Resizing or scaling the path, or offsetting it even by small fractional amounts prevents the program from crashing.

**Comment by kobalicek** [comment]
I will look into this

**Comment by kobalicek** [comment]
BTW I have looked into this already and thinking about a fix. This is actually caused by curve flattening logic that cannot handle well flattening of curve that has the same X (it still tries leftToRight vs rightToLeft) and is clipped at the same time.

I will most likely do a hotfix first so this case doesn't happen and then fix it properly.

**Comment by fjpietr** [comment]
I can confirm that the fix works, no crashes in both scenarios, renders as expected. Thank you!!!
