### ISSUE TITLE
GIMP is looking for a new vector engine

### ISSUE THREAD

**Issue by vinipsmaker** [blend2d/blend2d#65]
Hey guys, I just noticed GIMP developers started a new project out of dissatisfaction for cairo. Maybe someone here could reach out for them and they could use Blend2d instead. And the current driving force at their new library[1] could give a helping hand here. It seems the biggest concern for them is to support more colorspaces than just RGB.

[1] https://pippin.gimp.org/ctx/

**Comment by kobalicek** [comment]
Hi, thanks for sharing! 

I think the goals of `Blend2D` vs `ctx` are kinda incompatible - Blend2D was never designed to be as small as possible and to run on microcontrollers, it's basically a library that favors modern hardware and was designed for high performance from ground up (at the cost of being larger in size than those super embeddable libraries).

I think Blend2D would deserve some propagation, but on the other hand I like the low-profile mode that we are running at the moment as not all features are complete. When multithreading is implemented we would definitely share more benchmarks and let people know that we are faster again :)

**Comment by vinipsmaker** [comment]
> When multithreading is implemented we would definitely share more benchmarks and let people know that we are faster again :)

Right'o.

> I think the goals of `Blend2D` vs `ctx` are kinda incompatible - Blend2D was never designed to be as small as possible and to run on microcontrollers

I completely agree with you. I also noticed these incompatible goals before bringing the topic to your attention. But GIMP will never run on MCUs either. The reason for them to jump into ctx is just about colorspace. I should also have posted this link: https://www.gimp.org/news/2020/01/04/gimp-and-gegl-in-2019/#whats-new-in-gegl-and-babl

> The ctx library already has support for floating point pixel formats, and that support is geared to end up generic for gray, RGB, CMYK and other multi-component formats. Lack of support for color spaces and pixel encodings beyond 8-bit sRGB in cairo has been a gap for GEGL/GIMP that ctx can end up filling.

**Comment by dumblob** [comment]
Let me chime in here. I wrote the author of `ctx` (who is also a contributor to Cairo and GIMP) on 1. 11. 2019 pointing out there is Blend2D offering very similar capabilities, but faster. He didn't respond to anything GIMP related, but emphasized, that `ctx` is very much incomplete (don't know whether it still holds nowadays) and listed features which are missing.

So I feel at least one GIMP dev knows about Blend2D, but it would anyway be good to tell the GIMP project more "officially" about Blend2D.

I agree, that having less attention for Blend2D avoids tension etc., but on the other hand it would safe a lot of work to GIMP devs and everybody would profit from the quality and speed of the overall outcome, so I don't think we should try hard to "hide" Blend2D until e.g. multithreading is implemented (this is jist my personal opinion).

**Comment by kobalicek** [comment]
Based on my own experience I think trying to push Blend2D too much could become counterproductive. There is a small community around Blend2D and people that already use it for their projects are generally happy with the library and also patiently waiting for more features to come.

I think public announcements are okay, but I would generally avoid trying to convince other people to switch their projects to use Blend2D - switching libraries is always complicated and people responsible for that should do their own evaluation and make the decision based on their goals.

I would really welcome a completely different help - study Blend2D codebase and try to improve it as this is what matters most at the moment :)
