### ISSUE TITLE
MESA driver for Libre SoC could use parts of blend2d

### ISSUE THREAD

**Issue by dumblob** [blend2d/blend2d#66]
I just accidentally came across this call up for devs (they'll be paid):

http://lists.libre-riscv.org/pipermail/libre-riscv-dev/2020-January/003302.html

And thought Blend2D could actually be used for some operations. Of course, there is the dependency on AsmJIT which doesn't have full support for RISC-V yet (see e.g. in https://github.com/asmjit/asmjit/issues/232#issuecomment-457874699 ), but even then it could make sense to go this way.

@lkcl (if this is actually your account) any thoughts?

**Comment by kobalicek** [comment]
I don't really see how Blend2D could possibly be helpful in porting AMD drivers to RISC-V architecture. We don't implement any 3D functionality nor shaders as we only focus on high performance software-based 2D rendering.

If you have experience in this area maybe you can be a bit more specific about what you mean?

**Comment by dumblob** [comment]
Blend2D is an accelerated software renderer and that's what the Libre-SOC guys need (there is an overlap between 2D and 3D functionality). So at least the API architecture could be shared and probably some color_space/drawing/blitting/compositing/transformation/... operations as well (they get often transformed to 2D to allow easier computation).

But yeah, I didn't look into Libre-SOC requirements any further, so this might really be off. Bare with me :wink:.

**Comment by kobalicek** [comment]
Closing for now, anyone who wants to use Blend2D can do so :)
