### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by Arcnor** [blend2d/blend2d#7]
Hi,

I'm sure you've already noticed, but in case you haven't, the certificate for blend2d.com expired yesterday.

**Comment by kobalicek** [comment]
Yes it's unfortunate, I hope to get it fixed today, thank you!

**Comment by kobalicek** [comment]
The cert should be ok now

**Comment by Arcnor** [comment]
It is, although for 3 months :).

Thanks!
