### ISSUE TITLE
Undefined behaviour with atomic operations

### ISSUE THREAD

**Issue by digitalrave** [blend2d/blend2d#70]
Implementation uses type puning to perform all atomic operations. For example, blAtomicFetchAdd:
`return ((std::atomic<RawT>*)x)->fetch_add(n, std::memory_order_relaxed);`
This is undefined behaviour and should not be used. The fact that all calls to blAtomicFetchAdd operate on data declared with "volatile" keywords does NOT make this code valid in any way according to the standard, this is a common mistake. The current code might work on tested compiler versions but might (will) break on any update with hard to diagnose errors. In C++20 there is [std::atomic_ref](https://en.cppreference.com/w/cpp/atomic/atomic_ref) for such purpose, in older language versions there's no legal way to perform atomic operations on non-atomic objects, all such variables must be declared as std::atomic. The latter is the preferred solution actually even with C++20.

**Comment by kobalicek** [comment]
I think the construct is acceptable considering it uses a standard C++11 capabilities instead of using compiler-specific intrinsics, which are much uglier to use. And I think compilers are okay with it as Blend2D uses only machine word atomics, which have consistent alignment requirements across architectures.

I would also mention that Blend2D passes undefined behavior sanitizer, so I don't really see a problem in this case. It offers a C-API - so the headers cannot really use C++ constructs in exposed structs.

**Comment by digitalrave** [comment]
Well, technically type punning is not a standard C++11 capability, it is explicitly prohibited there :-) If current compilers are OK with it - well, this may change at any time. The problem with undefined behaviour is, er, that it is really undefined - the compiler is allowed to think it will never happen and optimize the code relying on this assumption, because if the assumption happens to be wrong - it doesn't care. This specific case with atomics is eligible for potential optimization assumption that the type puning code will never be actually reached upon execution. This will lead to some nasty bugs ranging from non-atomic access for some/all variables to even dropping entire logic code that operate with those variables (like reference counting). Again, these are potentially allowed effects. If currently tested compilers do not break the code and sanitizers do not scream... well, it's of course up to the developer to leave the undefined behaviour as is :-)
But I really think that declaring variables atomic is the right way to fix possible future bugs. It is ok in C++11, it is ok even for C API - they also have standard language atomics (apparently with different syntax)! Also for x86 an atomic load/save for primitive types is no more expensive than non-atomic one - using atomics just tells the compiler to prevent some instruction reordering which may lead to unsynchronized reads/writes.
I don't think I will be able to demonstrate failures in Blend2D from this issue, at least for now, but I kindly ask you to consider using just straight atomic variables. It seems it should not be much difficult to implement and it should not expose any runtime penalty (but this should of course be measured).

**Comment by kobalicek** [comment]
I would like to add here that Blend2D will use atomic_ref when compiling by a C++20 capable compiler, but older compilers will still use the current impl - casting to `std::atomic<T>` as there is no other cross compiler way of achieving this feature unless using builtins, which I would like to avoid.

**Comment by kobalicek** [comment]
I'm closing this as there is no refCount exposed to the public API anymore, so the public API is not affected by this and the internal API uses abstracted functions to work with atomics. There is most likely not even reason to use `std::atomic_ref` as well. Please reopen if you think this is still an issue.
