### ISSUE TITLE
Haiku OS compatibility

### ISSUE THREAD

**Issue by chatoune** [blend2d/blend2d#73]
The Haiku OS does not have a libc library, instead all those functions are in libroot.
CMakeLists.txt should take this inot account.

Regards,

Eddy

**Comment by kobalicek** [comment]
Thanks!

BTW do you have a small fix that works for you? I don't need PR, just something that you can verify would work, because I don't use Haiku and I have no way to test it.

**Comment by chatoune** [comment]
Yes,

In the CMakeLists.txt I have added Haiku specific flags
if (NOT WIN32)
  if (NOT HAIKU)
    list(APPEND BLEND2D_DEPS c m pthread)
  else ()
    list(APPEND BLEND2D_DEPS root m pthread)
  endif()
endif()

**Comment by kobalicek** [comment]
Does haiku need the other libraries like `libm` and `libpthread` or it's part of `libroot`?
