### ISSUE TITLE
Flush denormals to zero problem

### ISSUE THREAD

**Issue by kobalicek** [blend2d/blend2d#74]
Blend2D has problems when the CPU's FPU is set to flush denormals to zero. This is mostly related to our quadratic and cubic roots functions where we compare with `tMin` and `tMax`.

This issue originated from https://github.com/blend2d/blend2d-samples/issues/2

**Comment by atomsymbol** [comment]
Ok. So let's try the following on your machine:

    $ gdb /bin/bash
    (gdb) break _start
    (gdb) run
    (gdb) p $mxcsr

Output on my machine (note that it contains DAZ):

    $1 = [ DAZ IM DM ZM OM UM PM FZ ]

Interestingly, performing the same steps for `/bin/wc` yields `$1 = [ IM DM ZM OM UM PM ]`.

**Comment by kobalicek** [comment]
`$1 = [ IM DM ZM OM UM PM ]`

I think it's about custom compiler flags on Gentoo - some are hazardous like `-ffast-math` - Blend2D cannot work with `-ffast-math`, because it makes functions like isnan() to always return true, it's disastrous.

**Comment by atomsymbol** [comment]
I don't have `-ffast-math` in Gentoo's make.conf, but I do have `-fexcess-precision=fast`.

It may be the case that ELF binaries are somewhere storing what the initial value of MXCSR should be when the OS loads the binary. Do you happen to know whether this is the case?

**Comment by kobalicek** [comment]
I think it's very likely. The only needed thing in this case is to find a better tMin and tMas that would be stable for both FPU settings - because I'm a bit afraid that some other architectures like ARM may flush denormals to zero by default, so this has to be safe.

**Comment by atomsymbol** [comment]
... curiously, Valgrind's callgrind is unable to maintain the DAZ flag and sets it to zero when executing the code being profiled. `bl-qt-bounces` from blend2d-samples runs fine in callgrind on my machine.

**Comment by atomsymbol** [comment]
> I don't have `-ffast-math` in Gentoo's make.conf, but I do have `-fexcess-precision=fast`.
> 
> It may be the case that ELF binaries are somewhere storing what the initial value of MXCSR should be when the OS loads the binary. Do you happen to know whether this is the case?

make.conf also contained `-funsafe-math-optimizations`. Removing it, while retaining `-fexcess-precision=fast`, avoids the issue of DAZ being recorded somewhere in the executable and/or in shared libraries. Starting to rebuild key Gentoo packages now ...

**Comment by kobalicek** [comment]
I think no need to rebuild the system, what is needed is to prepare Blend2D for such environments and to override certain flags in CMakeLists so they are not used to build Blend2D itself. For example these two flags `-fassociative-math` and
`-freciprocal-math` are definitely not safe regarding Blend2D, but `-fno-signed-zeros` is safe.

Blend2D really relies on FPU operations being not reordered and that `isnan(x)` returns true if `x` is `NaN`, all other optimizations do not really matter. For example fusing multiply-add is okay too.

**Comment by atomsymbol** [comment]
> I think no need to rebuild the system, ...

Just a note: I am rebuilding it to improve the overall stability of the system. I will keep in my mind that `-ffast-math` and similar compiler options are tricky.

**Comment by kobalicek** [comment]
Thanks! Please reopen if the provided fix doesn't work.
