### ISSUE TITLE
The 'volatile' specifier is deprecated in C++20

### ISSUE THREAD

**Issue by Ptomaine** [blend2d/blend2d#77]
Hello Petr,

Using new GCC 10.1, with the initial support for C++20, there are warnings (and later will be errors) about using volatile variables in Blend2D, like this one:

```
rasterworksynchronization.cpp:30:9: warning: '--' expression of 'volatile'-qualified type is deprecated [-Wvolatile]
30 |   if (--jobsRunningCount == 0) {
```

It's recommended to move to the 'atomic' type.

**Comment by kobalicek** [comment]
Yeah, these will disappear. I have a futex branch, I will fix these in there first. Thanks!

**Comment by Ptomaine** [comment]
Please, keep in mind. If you're really going to use atomic then avoid using ++ operator on the atomic variables directly. This is because ++ operator uses fetch_add with the default std::memory_order_seq_cst parameter. You need to use fetch_add explicitly instead of ++ operator with std::memory_order_relaxed to gain the same speed with your code. The same thing about -- operator and fetch_sub.

**Comment by kobalicek** [comment]
I think this issue can now be closed as there is no `volatile` use anymore in Blend2D.

Atomics are now properly abstracted via blAtomicXXX with the most necessary memory ordering semantics required to implement atomic reference counting and also other operations used by Blend2D (bitwise operations).
