### ISSUE TITLE
Using nearest neighbor when rendering

### ISSUE THREAD

**Issue by artem-ogre** [blend2d/blend2d#78]
Is there a way to use nearest neighbour when rasterizing with blend2d?

**Comment by yzrmn** [comment]
Hi, do you mean rasterizing without anti-aliasing?

**Comment by artem-ogre** [comment]
Hi, Fabian. Yes, exactly :) I need to rasterize simulation data onto an image for a GIS application. So I evaluated if an existing rasterization engine could do the job. In this case any interpolation is undesired since values are physical parameters.

After doing more research it seems that it is not a good fit for my task: not only I need to be able to rasterize without aliasing I would also prefer a target where pixels store 32-bit floating points (also not available from reading the docs).

**Comment by kobalicek** [comment]
This is true, Blend2D currently provides out of box support for rendering into 8-bit 32-bit pixel formats that use 8-bit per component. And at the moment the only rasterizer we use is a high-quality rasterizer with does anti-aliasing. The support for more precise pixel formats will be provided in the future and non-aa rasterizer too, but at the moment we focus on other things, which are more important.

**Comment by artem-ogre** [comment]
Yes. I understand. It is indeed quite a niche use case that I have. :) Thank you for the reply!

**Comment by feuerste** [comment]
Looking forward to these two features, too! Keep up the great work!
