### ISSUE TITLE
show up BLImage

### ISSUE THREAD

**Issue by chouer19** [blend2d/blend2d#79]
how can I display the image when running my program? not just store it in .img.
I want to do some dynamic data visualization.

**Comment by yzrmn** [comment]
Hi, Blend2D does not have the capabilities to do so on its own.
You will need an UI toolkit like the Qt framework (or similar).
The [samples ](https://github.com/blend2d/blend2d-samples) might be a good starting point because some of them use Qt too.

**Comment by kobalicek** [comment]
Yeah, samples are good, but you can also use SDL, Linux framebuffer, DIB section (Windows), etc... There is many ways to put pixels on screen. Blend2D is really just the rendering, it doesn't deal with windowing systems.

**Comment by kobalicek** [comment]
I'm closing, reopen if you have more questions!
