### ISSUE TITLE
C API Help

### ISSUE THREAD

**Issue by kobalicek** [blend2d/blend2d#8]
This issue is provided for C-API users.

If you think that something in C-API is not documented well please add a comment here and we will try to update the documentation.

**Comment by speps** [comment]
A few things I've found while doing some bindings (still WIP):

* `blImageCodecBuiltInCodecs`: should either return `const` or actually do a weak assign onto an existing instance, in my binding that method looks like it'll have to be a special case when it really shouldn't be.
* `blFontLoaderDataByFaceIndex`: returns `BLFontDataImpl*`, seems like a big problem to me, leaking implementation details.

**Comment by kobalicek** [comment]
Thank you for your feedback. I think both issues are valid and I will fix them.

**Comment by kobalicek** [comment]
`blFontLoaderDataByFaceIndex` has been addressed - I think it makes more sense now.

**Comment by kobalicek** [comment]
`blImageCodecBuiltInCodecs` is gone as well. There are 2 new functions that can be used as a replacement:

  * `blImageCodecArrayInitBuiltInCodecs` (initializer)
  * `blImageCodecArrayAssignBuiltInCodecs` (use on existing valid instance)

**Comment by speps** [comment]
Awesome thanks a lot for this, great changes! I'll post my bindings somewhere once I'm done.

Side question: I'm currently using the blend2d-beta.zip link to download the source automatically when building my bindings, is it synced with the master branch?

**Comment by kobalicek** [comment]
The beta links are only snapshots that do not reflect the current git version. The idea is to make a new beta release when something changes and it's tested. For example today I will create a new snapshot as the API changed and I would like to propagate the change to users. I always bump the `betaN` number when releasing the new snapshot to make it more transparent when the snapshot is updated.

**Comment by martin31821** [comment]
@kobalicek Would you mind uploading your beta releases to github releases as well? This way users who are only watching releases will get notified whenever an API change was introduced.

**Comment by kobalicek** [comment]
Well I don't plan to add beta releases to github releases. I think it's too early to do this and I added beta source releases mostly for users that would like to evaluate Blend2D. I would recommend using master branch for users that want to use Blend2D at the moment

**Comment by kobalicek** [comment]
I think it's plan to close this issue, open a new one for anything new.
