### ISSUE TITLE
BLRgba32 isn't actually RGBA, but ARGB

### ISSUE THREAD

**Issue by jan-moeller** [blend2d/blend2d#81]
I was playing around with one of the examples and changed `ctx.setFillStyle(BLRgba32(0xFFFFFFFF))` to `ctx.setFillStyle(BLRgba32(0x000000FF))`, expecting it to be black. Unfortunately, this isn't black, but transparent blue.
I had to do `ctx.setFillStyle(BLRgba32(0xFF000000))` to get black.

**Comment by kobalicek** [comment]
This is true, Blend2D follows RGBA naming convention, but 32-bit `BLRgba32` and 64-bit `BLRgba64` internally store the color as `0xAARRGGBB` and `0xAAAARRRRGGGGBBBB`, respectively. The floating point  as this how it has been used for decades. However, the floating point representation `BLRgba` stores colors in `rgba` order.

It's possible to use the constructor, which follows the naming, so `BLRgba32(r, g, b, a)` would work as you expect.

**Comment by jan-moeller** [comment]
Alright, I'm not familiar with domain specific conventions, but to me this was surprising. Even more so as the actual constructor argument is called rgba, not argb, and I didn't see any clarifying comments anywhere. Therefore, to me, it seemed like an implementation detail that leaks through the interface.
Is the constructor taking a uint32 primarily meant to support interaction with other libraries, then?

**Comment by kobalicek** [comment]
Yeah, this can be considered an implementation detail, however, this is a very common format, for example SKIA's `SkColor` has the same order of components. So to answer the question, taking `uint32_t` is to make it easier to interact with other libraries and user code that uses the same convention.
