### ISSUE TITLE
How to draw to a gray image?

### ISSUE THREAD

**Issue by unbored** [blend2d/blend2d#82]
There is only RGBA and RGB, is A8 presenting a single channel format?
I tried the blend2d-samples, changed the format from `BL_FORMAT_PRGB32` to `BL_FORMAT_A8`:
```
#include <blend2d.h>

int main(int argc, char* argv[]) {
  BLImage img(480, 480, BL_FORMAT_A8);

  // Attach a rendering context into `img`.
  BLContext ctx(img);

  // Clear the image.
  ctx.setCompOp(BL_COMP_OP_SRC_COPY);
  ctx.setFillStyle(BLRgba32(0)); // have to set to 0 before clear
  ctx.fillAll();

  // Fill some path.
  BLPath path;
  path.moveTo(26, 31);
  path.cubicTo(642, 132, 587, -136, 25, 464);
  path.cubicTo(882, 404, 144, 267, 27, 31);

  ctx.setCompOp(BL_COMP_OP_SRC_OVER);
  ctx.setFillStyle(BLRgba32(0xFFFFFFFF));
  ctx.fillPath(path);

  // Detach the rendering context from `img`.
  ctx.end();

  // Let's use some built-in codecs provided by Blend2D.
  BLImageCodec codec;
  codec.findByName("BMP");
  img.writeToFile("bl-getting-started-1.bmp", codec);

  return 0;
}
```
Ran the code and found all the curves 4 times fatten, seems like a 4-channel image drew to a single-channel buffer.
Did I missed something?

**Comment by kobalicek** [comment]
At the moment A8 represents an alpha-only format (mask), not an arbitrary single-channel format. The problem with BMP is that it most likely doesn't support such format, so Blend2D stores it as ARGB32 BMP and this is most likely why you see 4 channels. Internally A8 format really is a single-channel alpha, so one byte per pixel.

Not sure if this deserves fixing - I think having PNG encoder implemented would fix that as PNG supports alpha-only images.

**Comment by unbored** [comment]
> At the moment A8 represents an alpha-only format (mask), not an arbitrary single-channel format. The problem with BMP is that it most likely doesn't support such format, so Blend2D stores it as ARGB32 BMP and this is most likely why you see 4 channels. Internally A8 format really is a single-channel alpha, so one byte per pixel.
> 
> Not sure if this deserves fixing - I think having PNG encoder implemented would fix that as PNG supports alpha-only images.

So at present it can't save to a normal single-channel grayscale format? I think BMP do have a 8-bit single-channel format other than alpha-only.

**Comment by kobalicek** [comment]
At the moment if you want to save to a gray BMP you would have to construct it yourself. I think there could be some option that would force A8 to Gray8 conversion for formats that do not support A8 natively.

**Comment by kobalicek** [comment]
I'm closing this as Blend2D doesn't offer greyscale images. The best way of creating greyscale images is to convert to such format from RGB.

Please reopen if necessary, but greyscale pixel formats are not on the roadmap at the moment as there are more severe features that need to be implemented first.
