### ISSUE TITLE
RadialGradient with multiple stops and different coordinates generates wrong image

### ISSUE THREAD

**Issue by sammycage** [blend2d/blend2d#84]
Cairo :
![bubbles](https://user-images.githubusercontent.com/29164324/88276620-440da000-ccd7-11ea-83a3-f618b3aac127.png)

[lunasvg-cairo.zip](https://github.com/blend2d/blend2d/files/4965306/lunasvg-cairo.zip)

Blend2d:
![bubbles](https://user-images.githubusercontent.com/29164324/88276697-68697c80-ccd7-11ea-8ecd-cf69a64ae0d1.png)

[lunasvg-blend2d.zip](https://github.com/blend2d/blend2d/files/4965313/lunasvg-blend2d.zip)

**Comment by kobalicek** [comment]
Interesting, looks like advancing the gradient is totally wrong in this case, will check it out.
