### ISSUE TITLE
New SPIR SPV_INTEL_vector_compute extension

### ISSUE THREAD

**Issue by LifeIsStrange** [blend2d/blend2d#85]
https://www.phoronix.com/scan.php?page=news_item&px=Intel-IGC-Vector-Backend

https://github.com/intel/llvm/pull/1612/files

This *could* revolutionize 2D rendering performance  (and/or efficiency) on Intel igpus (most of the market)

**Comment by kobalicek** [comment]
Maybe I'm missing something, but how would this help with software accelerated 2D rendering implementation?

**Comment by LifeIsStrange** [comment]
@kobalicek no idea, it seems that it would increase the amount of parallelism that can be achieved on compute tasks by being more SIMD friendly?
Feel free to close this issue as it will be a long time before we get blogs that explain it's behavior more in depth.

**Comment by kobalicek** [comment]
Indeed, but it seems this would be good for possible GPU or Compute implementations, which is something that I don't work on at the moment - once we get top software-based performance and features we can move forward and offer GPU implementation.

I will close this for now, thanks!
