### ISSUE TITLE
blPathSmoothCubicTo  error

### ISSUE THREAD

**Issue by abu-irrational** [blend2d/blend2d#89]
in  path.cpp
within the  blPathSmoothCubicTo() function

the following line
  BL_PROPAGATE(blPathPrepareAdd(self, 2, &cmdData, &vtxData));
should be
  BL_PROPAGATE(blPathPrepareAdd(self, 3, &cmdData, &vtxData));

**Comment by kobalicek** [comment]
Good catch, thanks!
