### ISSUE TITLE
image transformation bug

### ISSUE THREAD

**Issue by randomguy76845** [blend2d/blend2d#9]
Tried getting-started-4 and the whole image is brown.
I found that translation works, but rotation and scaling are not.

**Comment by kobalicek** [comment]
I'm not able to help without seeing the resulting image.

**Comment by randomguy76845** [comment]
This is from getting-started-4.

![bl-getting-started-4](https://user-images.githubusercontent.com/49557140/56066758-fbacc600-5da2-11e9-9543-c1c4dba74a98.png)

**Comment by yzrmn** [comment]
I cannot reproduce it with master or website download (Windows 10 and Visual Studio 2019).

@randomguy76845 What CPU are you using? Is your dev environment inside a VM?

**Comment by randomguy76845** [comment]
I've tried Visual Studio 2019, still same result.
I replaced my cairo backend for GUI subsystem with blend2d and everything else works except image transformation.
If everyone else have no problem, that means something is wrong with my environment.
No VM, this is Intel i5 processor.

**Comment by kobalicek** [comment]
I will try to make this easier to report such bugs. It still can be Blend2D issue. I would recommend for now using the git version (instead of the package) - I will upload a new package for downloads soon.

**Comment by kobalicek** [comment]
I did some digging and now I found the issue:
  - machine that has SSE4.1 but no AVX - problem in `PipeCompiler::vblendv8_()`

I'm not sure whether this is in AsmJit or Blend2D, but I will fix it.

**Comment by randomguy76845** [comment]
I just found out that my CPU is Clarkdale. It's before Sandy Bridge, that means no AVX. I forgot how old my computer is.

**Comment by kobalicek** [comment]
It's okay, Blend2D baseline optimization level is SSE2 (you need at least SSE2 capable CPU on x86 arch).

**Comment by kobalicek** [comment]
This commit fixes the issue: https://github.com/asmjit/asmjit/commit/872b23b3bae97f1fc0bd514c1c5968894d726dd9

**Comment by kobalicek** [comment]
I will make a new source release today with the fix, for now you can just pull the git sources.

**Comment by randomguy76845** [comment]
okay it works on getting-started-4. Adding some scaling operation also works. Need sometime to test my GUI.

**Comment by randomguy76845** [comment]
Found some bugs. I think it's better i start another issues since this one already solved.
