### ISSUE TITLE
blend2d crashes if BLFontFace is a global object

### ISSUE THREAD

**Issue by htmlui** [blend2d/blend2d#90]
Following sample would reproduce this.

#include <blend2d.h>

BLFontFace face;
int main(int argc, char* argv[]) {
  BLResult err = face.createFromFile("NotoSans-Regular.ttf");

  BLFont font;
  font.createFromFace(face, 50.0f);

  return 0;
}

**Comment by kobalicek** [comment]
This is most likely static initialization order, compiler / platform?

**Comment by htmlui** [comment]
@kobalicek Your commit fixed the issue. Thanks.
