### ISSUE TITLE
How do I apply a pattern along a path?

### ISSUE THREAD

**Issue by gwaldron** [blend2d/blend2d#94]
In particular, I'd like to render a road surface and repeat the image so it's aligned with the contour of the path.
Is this possible?

**Comment by kobalicek** [comment]
No this is not possible at the moment and it's not on the roadmap. I would of course review any contribution in this area, but at the moment I would not start implementing it as there are other features that have high priority.

**Comment by gwaldron** [comment]
Fair enough! Thanks. I'll look into it if I have time.
