### ISSUE TITLE
Potential ideas for speed up when used for complex UIs

### ISSUE THREAD

**Issue by dumblob** [blend2d/blend2d#95]
I just came across this: https://github.com/intel/fastuidraw .

Feel free to take a look and close this issue if there isn't anything related nor interesting for Blend2D.

**Comment by kobalicek** [comment]
I'm closing this as at the moment there are no plans to introduce GPU acceleration in Blend2D. Once we have all features in CPU pipeline we will start experimenting with GPU, most likely Vulkan.

**Comment by dumblob** [comment]
Ok.

Btw. there are several (many) different approaches and ideas how to "offload" it to GPU. Some more information is sketched in https://github.com/intel/fastuidraw/issues/61#issuecomment-628901113 and in https://github.com/intel/fastuidraw/issues/65 .

**Comment by kobalicek** [comment]
I think it's not possible to offload to GPU if your renderer uses CPU. Maybe on processors such as Apple M1 where the memory is shared, but in general the plan is not to do this. Instead, when time comes, there will be a new backend that would target GPU, which would mean that all operations will be performed on GPU and CPU would be only used as a serializer basically - similarly to how MT renderer works.

But I have no ETA for that - having a fully featured software-based renderer is the priority at the moment. GPU will come after the software renderer has all the features planned.

**Comment by dumblob** [comment]
>when time comes, there will be a new backend that would target GPU, which would mean that all operations will be performed on GPU and CPU would be only used as a serializer basically

There exist already such gems - e.g. [piet-gpu](https://raphlinus.github.io/rust/graphics/gpu/2020/06/13/fast-2d-rendering.html ) and [Spinel](https://fuchsia.googlesource.com/fuchsia/+/refs/heads/master/src/graphics/lib/compute/spinel/ ) and maybe [GPU path rendering](http://kunzhou.net/zjugaps/pathrendering/ ). It's worth studying their history as e.g. piet-gpu had several quite radical turns during its development based on unsatisfying measurements.
