### ISSUE TITLE
Abnormal saving of 24-bit BMP image

### ISSUE THREAD

**Issue by Xarvie** [blend2d/blend2d#97]
The drawing efficiency of GDI is 500 times higher than that of GDIplus, but GDI can only draw opaque BMP. Can Blend2d use 32-bit rgba when drawing, and output the mixed 24RGB BMP file after drawing?
I tried using the following code
     BLImage img(3000, 3000, BL_FORMAT_XRGB32);
The exported BMP file cannot be opened using Clion IDE.
In the properties of the windows right-click menu, you can see that the display is 24bit,
mspaint can be opened, but cannot be saved as
Is this a bug?

Blend2d is a very nice project, tks.

**Comment by kobalicek** [comment]
I'm not sure that Blend2D's BMP encoder can satisfy all possible decoders out there. It uses the following when encoding bitmaps:
  - `BL_FORMAT_A8` - bitmap header V1
  - `BL_FORMAT_XRGB32` - bitmap header V1
  - `BL_FORMAT_PRGB32` - bitmap header V4

Thus, if the decoder doesn't understand BMP header V1 it won't decode the image.

I think that an enhancement to be able to change the parameters of the encoder would be a good addition, so you would be able to specify some more details than what's now possible.

**Comment by Xarvie** [comment]
Okay, I think I should modify the gdi decoding options. Thanks for your answers.
