### ISSUE TITLE
The BLEdgeStorage bandCount and bandCapacity

### ISSUE THREAD

**Issue by LancerLix** [blend2d/blend2d#98]
Hello Petr,

I see that the bandCapacity was calculated by
`uint32_t bandCapacity = uint32_t(allocatedSize / sizeof(void*));`

but the bandCount is stand for the type BLEdgeList<int>, which means that the bandCapacity is twice bigger than bandCount at least.

so the judgment that when the storage was already allocated
`if (bandCount <= edgeStorage.bandCapacity())`
may cause a out-of-bounds access risk when the bandCount is bigger than the bandCapacity divided by 2.

**Comment by kobalicek** [comment]
Thanks, this was a good catch!
